### ISSUE TITLE
Error on downlaoding svg in "all" mode

### ISSUE THREAD

**Issue by stefan-leye** [igvteam/igv.js#1009] opened 2019-10-28 08:26 UTC
When I try to download an svg image, without selecting a chromosome (so "all" is selected), I get the following exception:

> Uncaught (in promise) TypeError: Cannot read property 'roiFeatures' of undefined
    at ViewPort._callee4$ (igv.js:20719)
    at tryCatch (igv.js:54)
    at Generator.invoke [as _invoke] (igv.js:280)
    at Generator.prototype.<computed> [as next] (igv.js:106)
    at asyncGeneratorStep (igv.js:724)
    at _next (igv.js:746)
    at igv.js:753
    at new Promise (<anonymous>)
    at ViewPort.<anonymous> (igv.js:742)
    at ViewPort.renderSVGContext (igv.js:20736)

**Comment by jrobinso** [comment] 2019-10-28 17:11
I can't reproduce this.  What version of igv.js are you using?

**Comment by jrobinso** [comment] 2019-10-28 19:01
OK, we found it, thanks for the report.

**Comment by stefan-leye** [comment] 2019-10-29 08:21
👍

**Comment by jrobinso** [comment] 2019-10-29 20:38
This should be fixed now.

**Closed by jrobinso** 2019-10-29 20:38 UTC
