### ISSUE TITLE
Unable to load VCF file in IGV.js

### ISSUE THREAD

**Issue by amolpshinde07** [igvteam/igv.js#191] opened 2016-05-18 04:23 UTC
Hi,
I am trying to load VCF as a variant track in IGV.js (Web Version) but we are unable to see any reads in UI. Please find attached files which are working fine on IGV (Desktop version) but unable to load in IGV.js (Web Version).
I am using below code to add VCF as a variant track.
`var  options = {
                 genome: "hg19",
                 locus: "muc1",
                 tracks: [
                     {
                         name: "Genes",
                         url: "//igv.broadinstitute.org/annotations/hg19/genes/gencode.v18.collapsed.bed",
                         order: Number.MAX_VALUE,
                         displayMode: "EXPANDED"

                     },{
                        name: "VCF",
                        type: "variant",
                        format: "VCF",
                        sourceType: "file",
                        url: "./data/vcf/result.vcf",
                        displayMode: "EXPANDED"
                      }

                 ]
             };

    igv.createBrowser(document.getElementById('igvDiv'), options);`

Please help me out.
[result vcf.zip](https://github.com/igvteam/igv.js/files/269650/result.vcf.zip)

**Comment by amolpshinde07** [comment] 2016-05-18 04:49
by looking into old issues , i am able to load my vcf file but everytime i need to go in IGV tools and create idx file of each vcf and then load it into IGV web. Is there any flag or way to create idx if not exist when its loading in IGV (Web Version) like it in IGV (Desktop version)?

I am using below code to load my vcf file.
`
                      {
                        name: "VCFlocal",
                        url: "./data/vcf/result.vcf",
                        indexURL: "./data/vcf/result.vcf.idx"
                      }`

**Comment by jrobinso** [comment] 2016-05-19 06:05
This is not possible, igv.js is just a client program running in the browser, it would not be possible to create an index on the server.  Additionally, tabix is recommended for VCF indexes,  the igv index (.idx) will work but not as efficiently.

How did you resolve the original problem posted?

**Comment by jrobinso** [comment] 2016-05-22 06:04
This should be fixed now in v1.0.0-rc1.   The problem was a test for bgzipped (tabix) files which relied on url endsWith(".gz").  This did not work with parameters.  Test was updated to look at extension of "path" portion of url.  Please test again, and if fixed comment or just close this issue.

**Comment by amolpshinde07** [comment] 2016-05-23 03:45
i just used below schema to load my vcf instead of original posted,
`{ 
name: "VCFlocal", 
url: "./data/vcf/result.vcf", 
indexURL: "./data/vcf/result.vcf.idx" 
}`

but now how can we draw selection on chromosome band after calling below code,
igv.browser.search(location.chr+":"+location.start+"-"+location.stop);

**Comment by jrobinso** [comment] 2016-05-23 04:44
I'm not sure  I understand the question.  You can't draw on the chromosome band.  It will automatically draw a red box around the current location.

**Comment by amolpshinde07** [comment] 2016-05-23 06:14
it's drawing red box on first time when its loading but later whenever i call search function then its not drawing red box around the current range/location passed through search function.

**Comment by jrobinso** [comment] 2016-05-23 18:34
I can't reproduce your problem.  Could you please open a new git issue for this problem, and include an html page that reproduces it?

**Closed by jrobinso** 2016-05-23 18:34 UTC

**Comment by amolpshinde07** [comment] 2016-05-24 04:53
may be due to #195 above issue is occurring.
