### ISSUE TITLE
narrowing width hides cursor guide, center line, track labels button , and zoom controls

### ISSUE THREAD

**Issue by paul-shannon** [igvteam/igv.js#752] opened 2018-10-15 16:53 UTC
Sorry if this has already been discussed, weighed and strategies set.

I sometimes use igv on a laptop with a few columns of a DataTable to its right.  This often leads to the disappearance of the  above-mentioned controls.  

Perhaps tersely labelled buttons could be used when browser width is insufficient for the whole display?  Other ideas?

Thank you!

**Comment by jrobinso** [comment] 2018-10-15 17:20
That is actually by design,  not necessarily a good design,  but it is on
purpose.  Driving use case was my tiny phone,  the idea is to remove
non-critical controls.

A more responsive design which reorganizes the controls would be better.

**Comment by paul-shannon** [comment] 2018-10-15 19:17
Maybe the zoom +/- icons could always be present?

**Comment by jrobinso** [comment] 2018-10-15 23:46
Yes, I agree those are critical.  If they are being hidden its a bug.

**Comment by jrobinso** [comment] 2018-10-17 03:40
@turner Is working on a better "responsive" implementation.     Using media queries.     We have a test version here:  http://igv.org/web/navbar_test/test.html.   It needs a little more work but we'll have more flexibility using Doug's approach.

**Comment by paul-shannon** [comment] 2018-11-15 00:05
@jrobinso, @turner - this responsive navbar solves all of my problems.  Has it been pulled into the standard branch?  I don't seem to pick it up with a git pull; grunt.

Related - I should know this by now, but don't: is there an igv.js version number encoded in the source code in any way?  Something like ````igv.version````?

**Comment by paul-shannon** [comment] 2018-11-16 12:59
@turner - thank you.  I just pulled and built the latest from the master branch.  I can see the new responsive layout of the navbar.   Very nice.

I won't be surprised if this turns out to be my error or misconception, but is it possible that the navbar's sense of the available width is inferred from window width rather than the width of the enclosing div?   I will try to reproduce this in a minimal example but for now, here (in a shiny app using a dashboard sidebar) is what I see.  Notice how the navbar controls extend beyond the bordered div in which the genome tracks are rendered.

![image](https://user-images.githubusercontent.com/2480712/48622598-1d249580-e95c-11e8-94a5-9454eb853cbd.png)

**Comment by paul-shannon** [comment] 2018-11-16 13:33
@turner  The navbar overflow seems to be (mostly) a css problem with my use of  RStudio/Shiny conventions.

But in the minimal demo attached below, some of the same phenomenon can be seen, with no shiny involved, as the screenshot shows.  Any suggestions?

![image](https://user-images.githubusercontent.com/2480712/48623820-abe6e180-e95f-11e8-9a52-bed6ee121ffa.png)

[hg38-navbar-bug-html.txt](https://github.com/igvteam/igv.js/files/2589429/hg38-navbar-bug-html.txt)

**Comment by turner** [comment] 2018-11-16 14:39
Paul your observation is correct. The navbar uses media-query breakpoints to achieve responsive behavior. Unfortunately media-query only knows about the viewport (window) and does not generalize to an arbitrary containing element (div). I am exploring approaches to fix this. 

One hack you could use it to either edit or add a new media-query in igv.scss with a "fake" window width that triggers the responsive breakpoint you need.

**Comment by paul-shannon** [comment] 2018-11-16 19:57
Thanks @turner.   media-query breakpoints are new ground for me - so I think I will wait on your explorations, and meanwhile advise my users to keep their browser windows wide.  Thanks, as always,  for all the great features of igv.js.

**Comment by turner** [comment] 2018-11-17 17:51
Media queries use the viewport as the trigger for swapping css classes. A simple hack would be to add an additional media-query - for example - for a viewport width of 1600px let's say - that does the css swapping currently in used for 800px. See the media queries at the bottom of igv.scss.

**Comment by paul-shannon** [comment] 2018-11-28 01:59
@turner @jrobinso 
I pulled from the master branch today and built the igvShiny widget.  The navbar looks and behaves great!

**Comment by turner** [comment] 2019-01-15 13:57
Fixed with commit e00f8464

**Closed by turner** 2019-01-15 13:57 UTC
