### ISSUE TITLE
Rendering BAM track with wrong locus if showRuler flag set to false

### ISSUE THREAD

**Issue by deepaksibar** [igvteam/igv.js#269] opened 2016-09-20 10:16 UTC
Hi,
I if set showRuler track to false and search locus (lets say chr1:149148642-149148666), then BAM track is rendered 
But on mouse hover on beginning and end of track window location displayed are 149148642 and 149148668. Means start location is correct but end location is not correct.

If i set showRuler track to true then end location displayed is 149148666.

Please let me know the reason, how to fix is issue.

Regards,
Deepak

**Comment by jrobinso** [comment] 2016-09-25 03:56
Hi, what version if igv.js are you using?

**Comment by turner** [comment] 2017-07-04 13:48
I cannot reproduce this bug. I am closing this issue.

**Closed by turner** 2017-07-04 13:48 UTC
