### ISSUE TITLE
Plot labels not displayed

### ISSUE THREAD

**Issue by Alex-Willenbrink** [igvteam/igv.js#872] opened 2019-03-06 20:06 UTC
I upgraded the igv library I was using from 2.2.1 to 2.2.5 and found that when I added bed tracks, they plotted successfully, but none of the labels for the plots showed up. Reverting back to 2.2.1 fixed this issue but I'm wondering if there's a parameter I need to add to my track objects in the newest version of the app to get the labels for the plots to display.

Thanks!

**Comment by jrobinso** [comment] 2019-03-15 06:02
This looks like a bug.  Labels are displaying for me, but centered on the feature and they can be scrolled out of view.    They should remain in view as long as any of the feature remains.   If this is not the issue you are seeing could you zip and attach an example bed file that reproduces the problem?

**Comment by jrobinso** [comment] 2019-03-15 06:09
Actually behavior is the same in 2.2.1 (name can be scrolled out of view).     So I need some clarification, and probably an example file for you.  In particular what exactly are you referring to re "labels for the plots"?

**Comment by Alex-Willenbrink** [comment] 2019-03-22 23:13
Here's 2 pictures showing the problem. Between the 2 pictures, nothing has changed on my end except for the library upgrade. 

![igv_2 2 1](https://user-images.githubusercontent.com/28259898/54857536-1bc5f980-4cbd-11e9-8a3d-d18c80e5e61a.jpg)
![igv_2 2 5](https://user-images.githubusercontent.com/28259898/54857537-1bc5f980-4cbd-11e9-923f-46be51ebf3b6.jpg)

**Comment by jrobinso** [comment] 2019-03-22 23:21
Hi @Alex-Willenbrink, this might be fixed.   Could you attach a test file, or try this distribution?

http://igv.org/web/snapshot/dist/

**Comment by jrobinso** [comment] 2019-03-24 05:05
Thanks for the report.  This is fixed in version 2.2.6, just released.

**Closed by jrobinso** 2019-03-24 05:05 UTC

**Comment by Alex-Willenbrink** [comment] 2019-03-25 22:26
Hey Jim, thanks for looking into this! 

However, did the method for loading tracks change from 2.2.1 to 2.2.6? When I upgraded from 2.2.1 to 2.2.6, igv couldn't load my tracks for some reason.

![image](https://user-images.githubusercontent.com/28259898/54958158-16152180-4f12-11e9-8b96-de92888595bf.png)

**Comment by jrobinso** [comment] 2019-03-26 05:46
@Alex-Willenbrink Apologies, not on purpose, and not with our test data.   Could you share a test case that reproduces this?
