### ISSUE TITLE
Tracks not redrawn when window resized

### ISSUE THREAD

**Issue by helgathorv** [igvteam/igv.js#256] opened 2016-09-07 17:23 UTC
Load any tracks, go to whole chromosome 1, stretch the window horizontally
=>
The navbar stretches accordingly, and so does the ruler, but there are issues with the track redraw. The right edge grey tab and the gear icon are drawn correctly in the resized location, but the track content is not redrawn. See gap in the attached screenshot.
<img width="1251" alt="screen shot 2016-09-07 at 1 21 33 pm" src="https://cloud.githubusercontent.com/assets/1265859/18321940/3267e3b8-74fe-11e6-8615-10d0b75b0f18.png">

**Comment by jrobinso** [comment] 2016-09-08 16:04
The problem is the scale (base-pairs per pixel) for the tracks are not changed due to a window size event, nor should it be in most cases.     What's needed is a check on the scale, with an upper limit such that the chromosome always fills the view.   The applicable check is in place in the zoomOut method,  abbreviated below

       chromosome = this.genome.getChromosome(this.referenceFrame.chr,
        chrLength = chromosome.bpLength;
        maxScale = chrLength / viewportWidth;

**Comment by turner** [comment] 2017-07-10 13:49
Fixed with commit 7bac442e

**Closed by turner** 2017-07-10 13:49 UTC
