### ISSUE TITLE
Squished View for BAM Files

### ISSUE THREAD

**Issue by david-ma** [igvteam/igv.js#160] opened 2016-02-25 06:32 UTC
Hi IGV Team,

Are there any plans to create a "Squished" view for BAM files, like in the Java version of IGV?

Thanks!

**Comment by david-ma** [comment] 2016-03-02 06:10
Oh! I worked out how to do it by changing the config when describing the BAM file. Just set:
alignmentRowHeight: 1

**Comment by jrobinso** [comment] 2016-03-02 07:08
Re-opening to add squish to track menu

**Comment by jrobinso** [comment] 2016-06-09 21:59
Proposed behavior for BAM files:
expanded:  alignment row height == default or value supplied in config
squished: alignment row height = 1
collapsed: alignments no shown, only coverage track

**Comment by chaninator** [comment] 2020-10-07 17:42
@jrobinso Has the "Squish / Expand" menu selection for bam tracks been added? Or is that still being planned?

**Comment by jrobinso** [comment] 2020-10-16 04:16
duplicate of #758 - fixed in master but not released

**Closed by jrobinso** 2020-10-16 04:16 UTC

**Comment by boyangzhao** [comment] 2021-09-12 06:53
Hi any updates on this? I see it was planned for 2.7.0 milestone and then got deleted. In loading the latest version of igv.js, I don't yet see this option. Thanks!

**Comment by jrobinso** [comment] 2021-09-12 19:50
It is definitely there, it has been for almost a year, see the screenshot, so I'm not sure why you aren't seeing it.   Could I see a screenshot of what your alignment track menu looks like.

<img width="428" alt="Screen Shot 2021-09-12 at 12 47 56 PM" src="https://user-images.githubusercontent.com/933148/133000801-0f372738-4e1b-4888-a1a5-a4c9eaadcbef.png">

**Comment by boyangzhao** [comment] 2021-09-13 19:07
Thanks! My mistake - I was viewing through the wrong options. I just reran the latest version, and see the same as your screenshot. I was initially using igv.js ported version from dashbio, and it seemed they didn't upgrade to the latest yet.
