### ISSUE TITLE
Get sequence for GFF3 feature returning 'null'

### ISSUE THREAD

**Issue by khuev** [igvteam/igv.js#1475] opened 2022-03-15 22:11 UTC
Hi, coming over from [this message to the Google group](https://groups.google.com/g/igv-help/c/gC3TnDe8Nbs/m/5YzR2VG7BQAJ).

Reiterating that I am able to use "Copy feature sequence" from the dropdown menu on a reference genome properly, but when I try to do the same with a GFF3 track that is uploaded locally, I instead get back 'null'. 

Using:
IGV-Web app version 1.6.1
igv.js version 2.10.1

Posting here to keep updated on this issue, or hopefully to find out that I'm making a simple mistake. Thanks so much!

**Comment by jrobinso** [comment] 2022-03-17 04:59
How large is the feature?  It looks like there is a 1MB limit, imposed in igv.js, and you want get any error message if the feature is larger than that.  However we do not write "null" in any circumstance, so that is confusing.   Its possible the browser itself is failing and writing "null" because the string is too large.

If you haven't could you try this with a feature of moderate size (< 1 MB)?   Also what browser are you using?  And if you are able to open developer tools to see the javascript console are there any errors?

In any event I will add an error popup if feature size exceeds 1MB.

**Comment by jrobinso** [comment] 2022-03-17 19:51
Oh, never mind, I found a GFF that reproduces this problem.  Now to see what's special about it.

**Comment by jrobinso** [comment] 2022-03-17 20:03
Well this is strange, I did see the error once, but can't repeat it with the same file and same feature.  "null" is written to the clipboard (but not by igv.js).

**Comment by khuev** [comment] 2022-03-17 20:12
Strange, thank you for looking into this! So this is consistently happening with two GFF3 files that I have. None of my features is larger than 12,250 bases, spread out over a region about 170,000 bases in length. In most cases they're only about 30 bases, as we are trying to create features where oligos would land for specific genes. I will be looking into developer tools from your suggestion soon, but what you described happening is exactly what's occurring on my end.

**Comment by jrobinso** [comment] 2022-03-17 21:17
If you want to share one of your GFF3 I'll try it, but there is almost no chance it is specific to a file.   Like I said I got it once.  Then I tried opening development tools to look for errors, found none, and since then I haven't been able to reproduce it.

**Comment by khuev** [comment] 2022-03-17 21:38
Gladly, here's a [link to a file](https://drive.google.com/file/d/1VdpIN7pFztgX_00fHTR5MzKz8UI5-Zcn/view?usp=sharing) on my Google Drive. 

I've tried again below with this exact file, looking at developer tools and I think I see an error now:

![image](https://user-images.githubusercontent.com/46617756/158898553-570c37a2-057b-4eb1-acf8-f8f1840aec1a.png)


Clicked "indexedFasta.js:140" and now see the below:

![image](https://user-images.githubusercontent.com/46617756/158898750-d80fe6c5-78c2-4097-bcdf-ed31745ba7f2.png)

Pasting lines 138 to 144 here in case it helps at all:

        const idxEntry = this.index[chr];
        if (!idxEntry) {
            console.log("No index entry for chr: " + chr);

            // Tag interval with null so we don't try again
            this.interval = new GenomicInterval(chr, qstart, qend, null);
            return null;

Does this look like an issue on our end from the way we've set it up? Appreciate the efforts in trying to resolve this.

**Comment by jrobinso** [comment] 2022-03-18 05:34
To run your exact test case I would need the fasta also, or is this  for one of our hosted genomes?

There's no error in the first screenshot, just warnings about map files which is normal.   However the second screenshot, and line 143 in particular, could well be implicated since that is a source for the value "null".   Nice catch.   I don't think is an error in how you set it up because I did reproduce it once,  some illusive timing bug.

I was working on the assumption that there was some problem with the clipboard API, it is very prickly,  so added an option to "view" the sequence as a workaround, the sequence in the popup text can be copied with ctrl-c.   This makes sense regardless of the cause of this bug because not all platforms support the clipboard API, and it can't be used on http pages.

**Comment by jrobinso** [comment] 2022-03-18 05:40
Ahh, maybe I a cause, related to the fasta.   Does your fasta use the name "4" or "chr4" for the sequence name?  It normally doesn't matter,  there is an alias mechanism setup up so these naming conventions can be used interchangeably.   However that mechanism is not used when copying sequence (that is an oversight, will be corrected).   So if the fasta has "chr4" for the name of this sequence you will get this "null" sequence every-time.

**Comment by khuev** [comment] 2022-03-18 05:45
We are using a track that's labeled "RefSeq Genes". I think that's the hosted genome for hg38 judging from the URL that appears when I click on the track name: "URL: https://s3.amazonaws.com/igv.org.genomes/hg38/ncbiRefSeq.sorted.txt.gz", so I'm not entirely sure what the FASTA contains. I think all of my GFF3 files use the naming convention "4" and not "chr4" though, in case a mismatch there with the FASTA file might also be a concern?

**Comment by khuev** [comment] 2022-03-18 05:48
But thank you so much for implementing a workaround, this will be super helpful!

**Comment by jrobinso** [comment] 2022-03-18 05:49
Yep, that's it, name mismatch.  I just pushed a fix.   I'm planning a release for other features this weekend and this will be included,  if you want to test to confirm this was the problem rename one of your gff lines to use "chr4" and test that feature.

The workaround "view features" would not have helped in this case.

**Comment by khuev** [comment] 2022-03-18 06:02
Ah I see what you mean, the mismatch was definitely the issue. Just tested two small GFF3 files side by side, one with "chr4" and one with "4"; the one with "chr4" worked. Thanks for spending all the time to help me figure this out! I'll do a more thorough check in the morning but IGV has been wonderful to use and really appreciate the work you've put into it.

**Comment by jrobinso** [comment] 2022-03-18 06:21
OK I'll close this issue, fix will be out early next week  (i.e. if will work with "4").   Glad you posted this it was definitely a bug.

**Closed by jrobinso** 2022-03-18 06:21 UTC
