### ISSUE TITLE
CRAM fetch size limit

### ISSUE THREAD

**Issue by taniagmangolini** [igvteam/igv.js#1805] opened 2024-05-10 13:42 UTC
I am receiving the following error when I try to load a CRAM file > 60 MB. This error not happens with small CRAMs: "data size of 69.528.070 bytes exceeded fetch size limit of 30.000.000 bytes".
I am also using indexURL option to set the CRAI file and I have tried a larger fetchSizeLimit:

                config = {
                    format: this.organism.files.mapping.name.includes('.bam') ? 'bam' : 'cram',
                    url: this.organism.files.mapping.url,
                    indexURL: this.organism.files.mappingIndex.url,
                    fetchSizeLimit: 1000000000
                };

I could see that is set a "hard limit" of 30000000 bytes at  igv.js-master/js/cram/cramReader.js. Why this limit is not adjustable?

**Comment by jrobinso** [comment] 2024-05-10 15:25
I can look into making it adjustable.    I am curious how you are hitting the default limit, this is the first report.   The size of the CRAM file is not the issue, many of our cram files are > 1 GB and some > 5 GB.

**Comment by taniagmangolini** [comment] 2024-05-10 16:32
I have tried to load the same files on the https://igv.org/app/ and got the same error. 
First I load the reference (NC_045512.2.fasta and NC_045512.2.fasta.fai). After that, I load a track with the CRAM and CRAI files.
One thing I noticed is that when I increase the zoom the error stops to happen.

**Comment by jrobinso** [comment] 2024-05-10 17:50
Yes,  you might try reducing the visibilityWindow, which defaults to 30kb.  For example add this to your configuration

```
visibilityWindow: 10000
```

**Comment by taniagmangolini** [comment] 2024-05-10 19:08
I have tried this parameter without success. Can I share with you the cram and the crai files by e-mail?

**Comment by jrobinso** [comment] 2024-05-10 19:24
Its not necessary,  I have made fetchSizeLimit configurable and the default 10000000. If you'd like to pull the latest code and build you can use it, or wait until the next release.   Alternatively you can use the development build at https://igv.org/web/snapshot/dist,  or the development webapp at https://igv.org/app-test

**Comment by taniagmangolini** [comment] 2024-05-10 19:34
Thank you! I have tried to load on the files on https://igv.org/app-test and I got the same error as the image attached:
<img width="1440" alt="Captura de Tela 2024-05-10 às 16 32 45" src="https://github.com/igvteam/igv.js/assets/25271048/04e4ad4d-a54e-4cb0-81fd-8ba7ec533f06">

**Comment by jrobinso** [comment] 2024-05-10 19:36
It might take some time for the app-test build to catch up,  try again in a
few hours.

**Comment by taniagmangolini** [comment] 2024-05-13 16:14
The adjust solved the error message, but seems to be some problem related to the bundle-cram because it cannot load the cram. After some time loading an error page is displayed.

<img width="1439" alt="Captura de Tela 2024-05-13 às 13 09 06" src="https://github.com/igvteam/igv.js/assets/25271048/a42b448b-2f0e-4554-a359-7ec4304ea4dd">

**Comment by jrobinso** [comment] 2024-05-13 16:40
That indicates your browser is running out of memory, most likely.  It is not an application error per se (igv.js or the cram bundle), and there is probably nothing we can do about it.   You might try using a BAM file.  This might work because it loads incrementally and downsamples the data as it loads.  To decode a CRAM the entire data block must first be loaded into memory.

**Comment by jrobinso** [comment] 2024-05-13 16:50
Also, visibilityWindow will not necessarily help with CRAM files as they are encoded in larger blocks, but might help with BAM files for very deep coverage.    How deep approximately is the coverage?

**Comment by taniagmangolini** [comment] 2024-05-13 17:29
It is highly variable, but usually the coverage is between  10-50x.

**Comment by jrobinso** [comment] 2024-05-13 17:36
That's not very deep at all.    If you could share an example cram & crai file I will look into this,  you can use our email igv-team@broadinstitute.org to send links,  I can also give you a secure dropbox link to upload the files.

**Comment by jrobinso** [comment] 2024-05-14 15:15
Thanks for the test data.  I can reproduce the issue here but do not have a solution.  The cram-js package makes thousands of requests for small bits of data,  then at some point the browser freezes.   This could be a consequence of the extreme coverage depth, which is on the order of 100,000X, but that is just a guess.   This is out of igv.js control,  you might open a ticket at https://github.com/GMOD/cram-js.   They will want a reproducible test case.

I did confirm that a BAM file will work.   It is slow to load but does eventually display the data.   You can speed up loading by setting a small visibilityWindow.

**Comment by jrobinso** [comment] 2024-05-14 17:20
I'm going to close this as there is nothing we can do in igv.js.

**Closed by jrobinso** 2024-05-14 17:20 UTC

**Comment by cmdcolin** [comment] 2024-05-20 21:43
@jrobinso I managed to load the users cram file in jbrowse 2 but it does have fairly high memory usage though. i might also get rid of the fetchsizelimit...it had perhaps good intentions but it causes nothing but trouble :)

do you know what version of the cram library you are using?

**Comment by cmdcolin** [comment] 2024-05-20 21:45
regarding the thing where the cram library is generating many many http requests: that is something we combat in jbrowse 2 using the http-range-fetcher library (which rob wrote in tandem with writing the cram library). ideally this library would not be needed though, it might be useful to create a solution in the cram-js library that batches requests

**Comment by jrobinso** [comment] 2024-05-20 22:12
Hi @cmdcolin , thanks for responding.   I updated the cram-js library to the latest from the repository before testing this.    

A range fetcher library makes sense, it would not only help with this problem but others as well.   I will check that out. 

@taniagmangolini You might consider checking out JBrowse as it can handle files of this type, whereas (at the moment) igv.js cannot.  @cmdcolin Can give you pointers to install instructions if you need them.
