### ISSUE TITLE
No 'Access-Control-Allow-Origin' header is present on the requested resource.

### ISSUE THREAD

**Issue by valleema** [igvteam/igv.js#1293] opened 2021-03-22 13:56 UTC
Hi,

I am trying to understand why I cannot load hg19 genome track.

In Chrome devtools, I can see this error:

`Access to XMLHttpRequest at 'https://s3.amazonaws.com/igv.broadinstitute.org/genomes/seq/hg19/hg19.fasta.fai' from origin 'https://my.website.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.`

Any help will be greatly appreciated 😃 

--Maxime

**Comment by jrobinso** [comment] 2021-03-22 15:58
@valleema I can't reproduce the error, that URL works fine for me and the CORS headers are set.  Sometimes CORS policy errors are not the underlying issue.  Is there anything else in the console?   Another place to look is the network tab,  the failed request will be in red font, clicking the "response" tab sometimes has information.

**Comment by valleema** [comment] 2021-03-22 16:15
Here is the info for `hg19.fasta.fai`.
![image](https://user-images.githubusercontent.com/55448719/112021868-085efa80-8b32-11eb-9fd4-49d68dd899e9.png)

What I do not get, is that it worked for months and few days ago it broke.

**Comment by jrobinso** [comment] 2021-03-22 16:29
Yes I can see there are no CORS headers in your response.   Is there a proxy or firewall that your requests are going through?  Proxies can sometimes strip out headers, if its removes the CORs headers (the headers that start with Access-Control) its not going to work.   Here's what I see.    

<img width="994" alt="Screen Shot 2021-03-22 at 9 23 59 AM" src="https://user-images.githubusercontent.com/933148/112023661-af22a700-8af0-11eb-92e3-e695b704636f.png">

**Comment by jrobinso** [comment] 2021-04-01 17:05
@valleema Were you able to determine why the CORS headers are getting stripped off the response?

**Closed** 2021-04-08 05:09 UTC

**Comment by valleema** [comment] 2021-04-14 09:32
Thanks @jrobinso for pointing me to the right direction.

For people with the same issue, stumbling upon this : yes it was my institute proxy which was stripping CORS headers. Long exchanges with sysadmins led to correcting the zealous proxy. Works like a charm now.

**Comment by Rehanbagwan007** [comment] 2025-12-14 15:18
Change Visibility Of Ports Private To Public and check again
