### ISSUE TITLE
BAM files look different in same place

### ISSUE THREAD

**Issue by slevkor** [igvteam/igv.js#558] opened 2018-03-20 09:50 UTC
Hi @jrobinso 
I get some wierd behavior when opening IGV.js 
here is the first time i open my application:
![image](https://user-images.githubusercontent.com/12125717/37647147-3affc920-2c34-11e8-80cf-7b871c0e4b90.png)
this is the second time: 
![image](https://user-images.githubusercontent.com/12125717/37647162-45b75ef0-2c34-11e8-895c-acc01353f05a.png)

each time it looks different 
track info:
{
colorBy:"strand"
format:"bam"
headers: *permissions*
indexURL:"https://s3.us-east-2.amazonaws.com/khaled-bam-files/5bb4ec2b-b3ca-416d-b1b4-a29599748c5d"
name:"Alignments"
sourceType:"file"
type:"alignment"
url:"https://s3.us-east-2.amazonaws.com/khaled-bam-files/22d7f3b6-4289-4f88-b275-9e8ac9dcc191"
}

file is on s3 bucket

each time it loads i see three(sometimes four) http requests
ranges of responses are
1 Content-Length:66217
1 Content-Range:bytes 0-66216/51970414
2 Content-Length:593989
2 Content-Range:bytes 6488103-7082091/51970414
(im ignoring OPTIONS)

i compared answers (its binary) and it is similar - only x-amz-id-2: ## is different because those are different requests..

am i missing something?
maybe anyone can help our here..

**Comment by jrobinso** [comment] 2018-03-20 18:30
I will look into it.   What version of igv.js are you using?   Is this file
public (will I be able to load it)?

**Comment by slevkor** [comment] 2018-03-20 19:48
This version is from master about two months ago.
And yes file is public - you can use link provided as url or download it...

**Comment by jrobinso** [comment] 2018-03-20 22:04
Lev, what locus do I use for the screenshot?

The black bar under the coverage track indicates that alignments were
downsampled,  however, that is strange as coverage doesn't look
particularly deep.

**Comment by slevkor** [comment] 2018-03-21 09:03
locus is chr7:140,453,036-140,453,236
what do you mean by downsampled? some data is missing?

**Comment by jrobinso** [comment] 2018-03-22 06:22
Deep coverage files are randomly downsampled.   Otherwise you'll crash your browser.   The coverage here is ~3780x.    Parameters are described here under Alignment track:  https://github.com/igvteam/igv.js/wiki/Tracks.    You can effectively turn off downsampling by setting samplingDepth to a very large number.   You won't like the performance though.

Having said that,  your file is a pathological case and has uncovered a bug in the downsampling, in particular, it downsamples too aggressively.  This is caused by the paired alignments overlapping each other in the same sampling bucket.   That bug will be fixed soon.

When working properly downsampling is random and gives you a good representation of all alignments.   The black bars under the coverage track indicate a downsampled bucket.   You can click it for the # of alignments removed.   Again, for this case, downsampling is not working well.

A related parameter is "maxRows".  This is the maximum number of alignment rows that will be displayed.   The canvas required to display many thousands of rows is large, again it might crash your browser if set too large.

**Comment by jrobinso** [comment] 2018-03-24 20:05
Sorry for the delayed response.   Your did bring to light a bug in downsampling that wasn't noticed previously.   To get the fix pull and build again, or use the beta distribution: http://igv.org/web/beta/.

As mentioned, you can turn downsampling off by setting a large samplingDepth,  but you risk running out of memory and freezing the browser.   If you do set a large samplingDepth you can offset the memory required by decreasing the height of each row  (property alignmentRowHeight).  For this locus, the following settings will show all alignments:  

```
{
                    colorBy:"strand",
                    format:"bam",
                    indexURL:"https://s3.us-east-2.amazonaws.com/khaled-bam-files/5bb4ec2b-b3ca-416d-b1b4-a29599748c5d",
                    name:"Alignments",
                    sourceType:"file",
                    type:"alignment",
                    url:"https://s3.us-east-2.amazonaws.com/khaled-bam-files/22d7f3b6-4289-4f88-b275-9e8ac9dcc191",
                    samplingDepth: 3000,
                    maxRows: 3000,
                    alignmentRowHeight: 5
                }
```

**Closed by jrobinso** 2018-03-24 20:05 UTC
