### ISSUE TITLE
Losing labels when zoom in/out

### ISSUE THREAD

**Issue by felipefahrion** [igvteam/igv.js#1898] opened 2024-10-02 17:35 UTC
Sometimes we are losing the labels applying the zoom, is there anything to handle with that?

Current state
<img width="1568" alt="Screenshot 2024-10-02 at 14 33 02" src="https://github.com/user-attachments/assets/d8efa3b9-4347-4f57-bdc7-1d1c513a7107">

After the zoom 
<img width="1572" alt="Screenshot 2024-10-02 at 14 33 08" src="https://github.com/user-attachments/assets/f9b18ee0-1a72-4680-a905-ae704b48003e">

**Comment by jrobinso** [comment] 2024-10-03 17:46
The comment about "that far back" refers to the "igv" project, where this issue was posted.  Nevertheless I think you will find this fixed in the latest version of igv.js.   Reopen if the problem recurrs with the current version.

**Comment by felipefahrion** [comment] 2024-10-03 18:00
@jrobinso I will check this. Thanks in advance!

**Comment by jrobinso** [comment] 2024-10-03 20:11
I can't reproduce this.  Can you make it happen at https://igv.org/app?  If so give me exact steps to reproduce, including exactly what locus to start at and exactly how you zoomed.

**Closed** 2024-10-25 05:18 UTC
