### ISSUE TITLE
tabix query with index need igv.browser object

### ISSUE THREAD

**Issue by lidaof** [igvteam/igv.js#375] opened 2017-06-27 23:00 UTC
Hi Dear Developer,
I'm trying to query tabix file with igv.js with index .tbi file located at same URL, but seems the new instance of FeatureSource will still depend on igv.browser object. is that possible to remove that dependency? thanks!
code:
![image](https://user-images.githubusercontent.com/102806/27613616-1850ae38-5b62-11e7-8cea-b65f5602f162.png)
error:
![image](https://user-images.githubusercontent.com/102806/27613621-1e68bb6c-5b62-11e7-9481-1b6d589f59c7.png)

**Comment by jrobinso** [comment] 2017-06-27 23:23
This should be fixed now.  See test/testTabix.js.   You can either pull and build from source, or use the beta distribution which is built automatically.

The specific query range in your screenshot did not have any features, if you think that is incorrect reply here.   I expanded the range and confirmed features.

BTW that looks like a "bedgraph" file, not a "bed" file.  If your intent is to plot the values in a bar chart or "wiggle" chart please treat as "begraph" and convert to bigwig.

**Comment by lidaof** [comment] 2017-06-28 04:45
Hi Jim @jrobinso , the region does have data, but seems the query returns an empty list, can you take a look?

<pre>
$ tabix http://vizhub.wustl.edu/hubSample/hg19/GSM429321.gz chr7:26733030-27694134 | head
chr7	26733355	26733357	0.909091
chr7	26733561	26733563	1
chr7	26734557	26734559	0.941176
chr7	26734685	26734687	0.923077
chr7	26734703	26734705	1
chr7	26735302	26735304	1
chr7	26735484	26735486	0.642857
chr7	26735530	26735532	0.785714
chr7	26735599	26735601	0.857143
chr7	26735665	26735667	0.909091
</pre>

**Comment by lidaof** [comment] 2017-06-29 04:08
Hi Jim, just curious would the size of .tbi would affect the returned results to be empty? Thanks.

**Closed** 2017-06-29 04:27 UTC

**Comment by jrobinso** [comment] 2017-06-29 04:31
I fixed the unit test,  you should use a FeatureFileReader for your purposes, not FeatureSource.   In general the "Source" objects do caching and other things specific to the igv browser instance.  For example they depend on "visibilityWindow" and will expand the requested range for efficiency.   The "Reader" objects just read.   I suggest you use the "Reader" objects and manage your own cache, if you want to cache.   This should minimize dependencies on the igv browser objects.    

You're the only person I'm aware of using igv.js in this way.

Look at testTabix.js for the details.

**Comment by lidaof** [comment] 2017-06-29 04:37
Thanks Jim. I though cache would increase the query speed next time. Is the
cache saved on user's computer? localStorage? How about for bigWig and
bigBed files? UCSC has the udcCache which improves querying speed of same
bigWig a lot for 2nd time query.

Yes, we are trying to reduce server side work for the browser. Thanks for
the igv.js library!

Daofeng

**Comment by lidaof** [comment] 2017-06-29 04:46
Also I just tested FeatureFileReader which works perfect. you may want to
close this case. Thanks for the tremendous help.

Daofeng

**Comment by lidaof** [comment] 2017-06-29 04:51
I just noticed tb.readFeatures('chr7', 26733030, 27694134) actually returns
data out of this range. say some of the data are exceed the stop position.
Not sure if this is a bug.

Daofeng

**Comment by jrobinso** [comment] 2017-06-29 05:05
igv.js is pure client code,  so the cache is in the browser memory.
That's why I suggest you use the "Reader" objects (e.g. FeatureFileReader)
as they do not do caching,  so you are free to implement in strategy you
choose.    The "Source" objects are a lttle too tied to igv.js usage
patterns and concepts such as "visibilityWindow".

**Comment by jrobinso** [comment] 2017-06-29 05:06
I'm not sure if its a bug or feature either,  but I think it should return
just the requested region.   It is probably returning everything in the
tabix blocks referenced.  I will add a filter to throw out features not
requested.   Thanks for noting it.

**Comment by lidaof** [comment] 2017-06-29 05:10
Thanks a lot for the clarification and fixing.

Daofeng
