### ISSUE TITLE
Use semantic versionning

### ISSUE THREAD

**Issue by romgrk** [igvteam/igv.js#617] opened 2018-04-10 18:51 UTC
I was reading some parts of the documentation sooner today, and I noticed that you've been making some changes in the 1.1 release, and some of them seem to be incompatible with the 1.0 release.

Semantic versionning is the standard versionning system for quite all javascript projects. It allows very simple communication of the compatibility of your API. 
E.g. at 1.0.0, if you're adding backwards compatible features, you just increase the middle number (1.1.0), but if you're making incompatible API changes you increase the major number (2.0.0). It allows developpers to confidently upgrade their IGV.js version on minor releases, and tells them upgrading a major release will require changes in their codebase.

The whole thing is explained very well here: [https://semver.org/](https://semver.org/) (see section "Why Use Semantic Versionning")

On a similar topic, having a per-version wiki would be nice :)

**Comment by jrobinso** [comment] 2018-04-10 19:03
Hi @romgrk We are using semantic versioning,  all changes should be backward compatible.  What specifically have you found that is not backward compatible?

Having said that,  the number of new features are substantial and we might bump this to 2.0.0.

**Comment by jrobinso** [comment] 2018-04-10 19:11
@romgrk -- yes per-version wiki would be nice.  I don't know an easy way to do that.   Using wiki for documentation is not idea,  but there is a very low threshold to creating it which is important since I do all the documentation,  as well as coding on 3 projects.

**Comment by romgrk** [comment] 2018-04-10 19:18
[Tracks Menu](https://github.com/igvteam/igv.js/wiki/Track-menu)
[Tracks Menu (1.1)](https://github.com/igvteam/igv.js/wiki/Track-menus-(v-1.1))

The `click` handler changes from `click` to `clickHandler`. 
(Also it's unclear in 1.1 if it should be `label` or `name/object`.)

If you're already using semver, you can close this. :)

**Comment by jrobinso** [comment] 2018-04-10 20:48
Thanks for catching that,  the problem is clearly defining what in the Wiki is part of the API and what is not.   The pages you reference are developer notes, basically notes to myself, but that is not clear.   I will leave this issue open as a reminder to clearly delineate the API,  which consists of the pages  "API",  "Browser",  and "Tracks".

**Comment by jrobinso** [comment] 2018-04-10 22:16
I've made a stab at delineating the API on the wiki.   I will close this but thanks again for raising the issue.

**Closed by jrobinso** 2018-04-10 22:16 UTC
