### ISSUE TITLE
GtexSelection; gene.toUpperCase is not a function

### ISSUE THREAD

**Issue by ecolijpb** [igvteam/igv.js#1357] opened 2021-08-12 20:12 UTC
Using embedded igv.js v2.9.4
package.json
`"igv": "^2.9.4"`

When searching for a valid locus tag
![image](https://user-images.githubusercontent.com/88856259/129261520-3035e0bb-58c4-444d-962f-5e91621d71e0.png)

An error of `toUpperCase is not a function` is presented
![image](https://user-images.githubusercontent.com/88856259/129261867-e815c252-35cc-4750-9098-021ab804b0bf.png)

I can track this down to the `GtexSelection` constructor
```
igv.js:63633 Uncaught (in promise) TypeError: gene.toUpperCase is not a function
    at new GtexSelection (igv.js:63633)
    at igv.js:64076
    at Array.map (<anonymous>)
    at createReferenceFrameList (igv.js:64062)
    at Browser.search (igv.js:66608)
```
```javascript
   constructor(gene, snp) {
        // <snip>

        if (gene) {
          this.gene = gene.toUpperCase();
          this.geneColors[this.gene] = brewer[this.genesCount++];
        }
```
`gene` is being treated as a `string`, but in my case it is an `object` with the following shape.
```json
{
  "id": <string>,
  "name": "HTZ1",
  "type": "gene",
  "chr": <string>,
  "start": <number>,
  "end": <number>,
  "score": 0,
  "strand": "+",
  "attributeString": <string>,
  "delim": "="
}
```

**Comment by jrobinso** [comment] 2021-08-12 22:36
I'm trying to reproduce this, but so far unsuccessfully.   What genome
assembly is this for?  And have you customized the search service?

**Comment by ecolijpb** [comment] 2021-08-13 16:20
I'm using a GFF3 file as input

The relevant entry is
```
chrXV.0    BioCantor    CDS    310044    310448    .    -    0    ID=4a571ba6-e8e8-016a-7c9a-a7c76fa26eab-1;Parent=cbdfc17e-f204-5d7a-c320-c82b3a37cf7b;adj_start=310043;adj_stop=310448;alignment_id=HTZ1-0;exon_annotation_support=1;gene=HTZ1;gene_biotype=protein_coding;gene_id=MyGenome_G0005440;gene_name=HTZ1;gene_symbol=HTZ1;locus_tag=MyGenome_G0005440;proper_orf=True;source_gene=S000005372;source_gene_common_name=HTZ1;source_transcript=HTZ1;source_transcript_name=HTZ1;transcript_biotype=protein_coding;transcript_class=ortholog;transcript_id=MyGenome_T0005440;transcript_modes=transMap;transcript_name=HTZ1;valid_start=True;valid_stop=True
```

No search service customization

**Comment by jrobinso** [comment] 2021-08-13 16:45
Thanks, after fixing the missing tabs I loaded that as gff3 and was able to search for "HTZ1" without an issue.    If you can zip up a self contained test case that reproduces the problem I will investigate further.  You can avoid the need to reference your fasta by changing "chrXV.0" to, for example, "chrX", then just use "genome: "hg38"" as a reference.

**Comment by ecolijpb** [comment] 2021-08-19 16:23
Please see the attached for a minimalist angular project that reproduces the issue.

See the `igv-wrapper` component. Included are fasta/gff3 dummy files. The text to search for is `G3N3`, that will reproduce the issue.

[angular-igvjs-1357.zip](https://github.com/igvteam/igv.js/files/7016058/angular-igvjs-1357.zip)

**Comment by jrobinso** [comment] 2021-08-20 03:27
Thanks for the test case, I wasn't able to use it as I do not use or know anything about Angular, but I was able to reproduce it with your gff3 file.    The problem is specific to gff3 files with certain characteristics.   I have pushed a fix to master.

**Closed** 2021-08-20 03:26 UTC
