### ISSUE TITLE
Ability to load/generate RNA secondary structure tracks?

### ISSUE THREAD

**Issue by rjandr** [igvteam/igv.js#730] opened 2018-09-04 15:05 UTC
The desktop version of IGV is capable of generating and visualizing base pair (BP) tracks which depict RNA secondary structures as arc diagrams. I was unable to determine if this is possible (or planned) for igv.js, any plans to make it a thing?

**Comment by jrobinso** [comment] 2018-09-04 15:51
Everything will eventually be added, but there is a long list.  I would, of course, welcome a pull request.

**Comment by jrobinso** [comment] 2018-09-24 18:28
Hi @rjandr I'm implementing this now, but am unsure of the rules on arcs.   The Java code does not translate directly.    I don't work in this field,  generally speaking is it expected that arcs are semi-circles?  

@shapemapper any comments on the rules for arc styles?   I'm porting your code to igv.js,  its not a straight port because the path functions in AWT and Javascript canvas are not identical.   Its easier for me to work from the rules you used.

**Comment by shapemapper** [comment] 2018-09-24 20:06
not quite sure what you mean by "rules", but yes - semi-circular arcs are the look I'm going for, and they are used by others in the field. They're not strictly semicircles since they have an interior hole. Or to say it a different way, the inner and outer edges of the arc are semicircles.

**Comment by jrobinso** [comment] 2018-09-24 20:09
@shapemapper By "rules" I mean constraints on the paths,  so yes semi-cicrular arcs answers my question.   The Java implementation uses general paths and I couldn't quite work out for sure that these paths were arcs, although every example I have seen are.   I'll code something up and might ask you to comment then.

**Comment by shapemapper** [comment] 2018-09-24 20:11
sounds good. happy to help

**Comment by jrobinso** [comment] 2018-10-02 20:36
I've added initial support for ".bp" files.  Currently it uses semi-circular arcs.    @shapemapper Do you have data from the paper https://www.cell.com/cell/fulltext/S0092-8674(16)30422-6#secsectitle0130  in ".bp" format?  It would be nice to use some public data to illustrate this new (for igv-web) track.

**Comment by jrobinso** [comment] 2018-10-02 20:49
You can test this BTW at igv.org/app,  just load the ".bp" file from the "Load Track" dropdown.

**Comment by jrobinso** [comment] 2018-10-03 17:32
Steve, could you elaborate on the issue you had with loading a fasta file?   I do it all the time.   Some screenshots might help.

**Comment by jrobinso** [comment] 2018-10-03 17:45
RE sorting,  to do this generally I need to assign a score to each feature.   I am inferring from your comment that the order of the colors imply a score, from lowest -> highest probability.

This track will be general, also supporting bedPE,  I don't want to hard-code "bp" format conventions in the track but can assign a score to the feature as they are parsed based on color order.

**Comment by jrobinso** [comment] 2018-10-03 18:01
@shapemapper The webapp can't write to a local file, and that's not really its role.  You can use igv desktop for that or write a script.   The main use case for the web app would be sharing data views.   Take note of the "Share" button on the app, you can drop files in dropbox, google drive, or nearly any webserver and create these links.    For day to day research on your own data IGV desktop is still the best option for most people.

**Comment by shapemapper** [comment] 2018-10-03 18:31
Oh okay, that makes sense.

________________________________

**Comment by jrobinso** [comment] 2018-10-03 18:33
@shapemapper When you have time please elaborate on the fasta problem, perhaps with a screenshot showing how you are loading it.   There could be a bug,  or could be a problem with our documentation, either way, I would like to fix it.

**Comment by shapemapper** [comment] 2018-10-03 18:34
will do after lunch

________________________________

**Comment by shapemapper** [comment] 2018-10-03 19:31
I should add I'm clicking `Genome`->`Local File ...`

________________________________

**Comment by shapemapper** [comment] 2018-10-03 19:32
The dialog opens fine, I select the HIV genome .fa file, then it just silently fails. If I open the web console, it points to an error with "Couldn't find initial locus".

________________________________

**Comment by jrobinso** [comment] 2018-10-03 19:46
OK,  I reproduced it.  You need an indexed fasta, and you have to select both the fasta and the index.

This is a bug, we should popup a warning,  but if you select both fasta and index (.fai) file it should work.   

<img width="229" alt="screen shot 2018-10-03 at 12 44 46 pm" src="https://user-images.githubusercontent.com/933148/46435052-48378a80-c70a-11e8-8b06-97a14f1204d1.png">

**Comment by shapemapper** [comment] 2018-10-03 20:01
okay cool

________________________________

**Comment by shapemapper** [comment] 2018-10-03 20:12
We have an off-by-one error in arc rendering. For example, line 917 of the attached bp file is

HIV-1_NL4-3    1    3    55    57    2

indicating a 3-nucleotide long arc with a 1-based inclusive left span of [1...3] and a right span of [55...57].

This is rendered correctly on desktop, but online the arc stops a nucleotide short on the right side of both ends - it's rendered as if it goes from [1,2] to [55,56].

________________________________

**Comment by jrobinso** [comment] 2018-10-03 20:19
OK, I see the bug.

**Comment by jrobinso** [comment] 2018-10-03 21:05
Example of a shared session, file is on Dropbox.    http://bit.ly/2NlBbLJ

I'm going to close this issue,  I opened a separate issue on the Fasta file.

**Closed by jrobinso** 2018-10-03 21:05 UTC
