### ISSUE TITLE
IGV no longer working with oauth tokens provided by promise

### ISSUE THREAD

**Issue by zarsky-broad** [igvteam/igv.js#1099] opened 2020-04-27 18:49 UTC
We [pass a promise to IGV to get a bearer token](https://github.com/DataBiosphere/terra-ui/blob/dev/src/components/IGVBrowser.js#L30), and today one of our users noticed that it's no longer working; looking in the browser, the requests for the file are being made with the header `Authorization: Bearer [object Promise]`. Rolling back to [version 2.3.5 from 2.5.2](https://github.com/DataBiosphere/terra-ui/pull/2116) fixes the problem.

**Comment by jrobinso** [comment] 2020-04-27 20:34
OK thanks.   Did you really have to roll back all the way to 2.5.2, or is
that just what you had before?  Will look into it.

**Comment by zarsky-broad** [comment] 2020-04-27 20:35
That was the version we were running when we last touched it, I didn't test with the versions in between.

**Comment by jrobinso** [comment] 2020-04-27 20:40
OK I'll find it, thanks for the report.

**Comment by jrobinso** [comment] 2020-04-27 21:55
OK, found it.  A Promise works, as does a function, but a function returning a promise does not.   I'll push a fix shortly and do a point release, which will be 2.5.4.

**Comment by jrobinso** [comment] 2020-04-27 22:57
Fixed with commit 9164687293fbe05895dc7a9c3d8bb6831ebdab43

**Comment by zarsky-broad** [comment] 2020-04-29 19:41
With the newest version, I'm seeing this: `Authorization: Bearer () => Object(src_libs_ajax__WEBPACK_IMPORTED_MODULE_8__["saToken"])(namespace)`

I only see that on the `?alt=media` calls, there are also `?alt=media&altMedia=true` calls that appear to have the correct token.

**Comment by jrobinso** [comment] 2020-04-29 20:23
@zarsky-broad I don't know where that would be coming from, we do not use WEBPACK at all.  Verify that your function is returning a promise for the oauth token.   It looks like it is returning something else.

**Comment by zarsky-broad** [comment] 2020-04-29 20:25
Indeed, the webpack part is us, but it look like it returning an uncalled function. This is with the same code that works with the old version.

**Comment by jrobinso** [comment] 2020-04-29 20:28
If you can setup a test case for me to try I will do so, you can use my Broad email for details.

The function must return a Javascript Promise,  this might be a change from the previous release.   Does it return a Promise?

**Comment by jrobinso** [comment] 2020-04-29 21:01
Perhaps you are returning a non Promise thenable?  I just pushed a change to support that, our doc says Promises but supporting thenables is not difficult.   Your Webpack might be doing something weird with async/await functions, just a guess,  I abandoned Webpack for that and other reasons.

In any event these are patterns tested which should now work.  If you're case isn't working after a fresh pull and build  I need to know what exactly your function is returning.

```

function () {return "the token"}

function () {return Promise.resolve("the token....")}

function () {return {
     then: function(resolve, reject) {
                  resolve("the token");
         })
  }
```

**Comment by jrobinso** [comment] 2020-04-29 21:17
You can use one of the build artifacts here to test  https://igv.org/web/snapshot/dist/

**Comment by panentheos** [comment] 2020-05-06 13:01
Hi Jim, Isaac pointed me at this issue. In our usage, we're setting the oauth callback globally, rather than per-track. I think that ends up calling `getOauthToken` here, after the promise handling code has already run. For our usage pattern to work, that code path would need to handle possible promise-returning functions in addition to plain values (perhaps by swapping the order with the code just above it)
https://github.com/igvteam/igv.js/blob/master/js/igvxhr.js#L140

Also FYI, instead of explicitly detecting promises, you can rely on the fact that using `await` on a non-promise value will just pass the value straight through. So for example, with a variable `v` that might be a plain value, a promise, a plain function, or an async function, the expression 

```
await (typeof v === 'function' ? v() : v)
```

would cover all the cases and give the final value.

Thanks for looking into this!

**Comment by jrobinso** [comment] 2020-05-06 16:55
@panentheos OK I will look into the global case.  Are you looking at the latest code?  Explicit Promise detection was removed several commits ago.

**Comment by panentheos** [comment] 2020-05-06 17:10
You're right, I must have been looking at older code WRT promise detection.

**Comment by jrobinso** [comment] 2020-05-06 19:23
@panentheos Let me be clear on what you are doing,  how exactly are you setting the global token (there have been several methods over the years), and what are you setting it to?  I'm inferring a function that returns a promise.   I want to test your case specifically.    igv.js has gone from old-school callbacks,  to Promises, and now to async/await,  some things might have been dropped in the transitions.

**Comment by panentheos** [comment] 2020-05-06 19:34
Here is our implementation: https://github.com/DataBiosphere/terra-ui/blob/dev/src/components/IGVBrowser.js#L30

The `saToken` function returns a Promise that resolves to an auth token. It automatically manages and refreshes the token over time, so the intention is to call it immediately before every use, in order to get the most up-to-date token.

**Comment by jrobinso** [comment] 2020-05-06 19:36
OK, got it.   I will setup a simulation of this.  I haven't yet figured out a way to unit test oauth.

What version of igv.js are you currently using?

**Comment by jrobinso** [comment] 2020-05-06 20:46
Reopen to fix global token

**Closed** 2020-05-06 20:48 UTC

**Comment by jrobinso** [comment] 2020-05-06 20:50
@panentheos OK this should be fixed now for global tokens.   I like your await suggestion, simplifies the logic and even works for "thenables".  

Not related to this issue, but the same options are now available for specifying urls.   Namely string, function, promise/thenable, function that returns promise/thenable.

**Comment by jrobinso** [comment] 2020-05-06 20:50
@panentheos I will do a point release for this in the next day or so as its a regression.
