### ISSUE TITLE
VCF loaded but not the corresponding VCF.gz (without VCF.gz.tbi)

### ISSUE THREAD

**Issue by antonylebechec** [igvteam/igv.js#1421] opened 2021-11-13 00:10 UTC
Dear IGV Team,

I use dceoy/igv-webapp docker image to load my data through https://github.com/igvteam/igv.js-flask.git (docker service named "DAS")

I perfectly load BAM, CRAM and BED files.

However, I've some problems to load VCF files.
I used multiples VCF files (*vcf and *vcf.gz), all passing BCFTOOLS "validation" (no error when "view" and "sort")
They all work using Tracks > Local Files...
When I used these files through the "DAS" service (and a json file):
- all *vcf files are correctly loaded, 
- all corresponding *vcf.gz with associated *vcf.gz.tbi are correctly loaded,
- but corresponding *vcf.gz without associated *vcf.gz.tbi are not.

Here are few examples:
ACROMETRIX.final.vcf OK
ACROMETRIX.final2.vcf OK
ACROMETRIX.final3.vcf OK
ACROMETRIX.final4.vcf OK
ACROMETRIX.final.vcf.gz KO
ACROMETRIX.final2.vcf.gz KO
ACROMETRIX.final3.vcf.gz KO
ACROMETRIX.final4.vcf.gz OK

[examples.tar.gz](https://github.com/igvteam/igv-webapp/files/7530987/examples.tar.gz)

Here is a screenshoot of IGV-web:
<img width="2105" alt="Capture d’écran 2021-11-13 à 00 40 39" src="https://user-images.githubusercontent.com/40463532/141595856-48cdb7d6-805f-413a-a2fe-b9e6c62aca05.png">

All *vcf are loaded. Only 1 *vcf.gz is correctly loaded (ACROMETRIX.final4.vcf.gz), because of some removed annotations (INFO and FORMAT). The only difference between ACROMETRIX.final4.vcf.gz and ACROMETRIX.final3.vcf.gz is "FORMAT/PL" annotation. 
Javascript error message for ACROMETRIX.final.vcf.gz:
"Malformed VCF header line: ##INFO=<ID=PZScore-HEMATOLOGY,Number=.,Type=Integer,Description="Prioritization Score for filter 'HEMATOLOGY', depending on th" (igv.min.js:39)

As there is no error message (e.g. window message), it's dangerous to load *vcf.gz files (without associated tbi), because no variant loaded does not mean there is no variants! A Javascript message informs that "Warning: index file not specified.  The entire vcf file will be loaded." (igv.min.js:39), but it seems that it's not the case.

I'll change my code to force *vcf.gz.tbi with *vcf.gz, but it could be great to either fix or prevent loading *vcf.gz without *vcf.gz.tbi.

Best regards

**Comment by jrobinso** [comment] 2021-11-13 03:19
I can't reproduce the issue.  All 4 of these configurations work for me (see screenshot).
<img width="1786" alt="Screen Shot 2021-11-12 at 7 17 08 PM" src="https://user-images.githubusercontent.com/933148/141603864-f66337af-6396-49cc-8462-ee40681bfb30.png">


```
            tracks: [
                {
                    type: 'variant',
                    format: 'vcf',
                    url: '../../Downloads/examples/ACROMETRIX.final2.vcf.gz',
                    indexURL: '../../Downloads/examples/ACROMETRIX.final2.vcf.gz.tbi',
                    name: 'Gzipped vcf - indexed'
                },
                {
                    type: 'variant',
                    format: 'vcf',
                    url: '../../Downloads/examples/ACROMETRIX.final2.vcf.gz',
                    indexed: false,
                    name: 'Gzipped vcf - indexed: false'
                },
                {
                    type: 'variant',
                    format: 'vcf',
                    url: '../../Downloads/examples/ACROMETRIX.final2.vcf.gz',
                    name: 'Gzipped vcf - no index'
                },
                {
                    type: 'variant',
                    format: 'vcf',
                    url: '../../Downloads/examples/ACROMETRIX.final2.vcf.gz',
                    indexURL: null,
                    name: 'Gzipped vcf - indexURL: null'
                }
```

**Comment by jrobinso** [comment] 2021-11-13 03:21
BTW you did not specify a version for igv-webapp or igv.js.   I am using the latest.

**Comment by antonylebechec** [comment] 2021-11-13 12:26
Thanks for that!

First, I used the latest release (just rebuild docker images yesterday) :
IGV-Web app version 1.6.3
igv.js version 2.10.4

I tried without "indexURL" and with "indexed: false", but I got the same problem.

You're probably right, it can be a problem with igv.js, suggesting that vcf.gz file is truncated from the source. There files are not huge, and BAM files (huge) are well loaded. Maybe a bgzip decompression problem?

**Comment by antonylebechec** [comment] 2021-11-13 12:28
Just a comment regarding "RefSeq Genes": it is not well aligned...
but GENCODE Genes is

**Comment by jrobinso** [comment] 2021-11-13 16:12
If you attempt to load a file that is huge without an index there could be errors due to the browser running out of memory.  igv.js will never see these errors, so there is no way to display a message.   Can you reproduce the problem with the exact files you zipped and sent me?   As I pointed out above they work perfectly for me, as you can see with the screenshot.   

I don't understand the comment about RefSeq genes.

Without a use case I can reproduce I am going to close this as there doesn't seem to be any client side errors.

**Closed** 2021-11-16 23:38 UTC
