### ISSUE TITLE
Codon information for `RefSeq Genes` track

### ISSUE THREAD

**Issue by mmanokhov** [igvteam/igv.js#1254] opened 2021-01-13 17:44 UTC
Desktop version of IGV shows codon information on 'RefSeq Genes' track. It would be nice to see the same information in web version too. Is it feasible to add codon information in igv.js lib for 'RefSeq Genes' track?

<img width="1096" alt="codon_info" src="https://user-images.githubusercontent.com/2229434/104487507-41349d80-55de-11eb-9fa7-374bf259f33d.png">

Thanks.

**Comment by jrobinso** [comment] 2021-01-13 17:46
There is already an issue open for this.   Yes its feasible,  I don't know when I will get to it.

**Comment by jrobinso** [comment] 2021-01-13 17:47
duplicate of #1069

**Closed by jrobinso** 2021-01-13 17:47 UTC

**Comment by DustBytes** [comment] 2023-01-10 10:39
Hi.

It's marked as completed.
How to view this on refseq? Can't find any option in Wiki.

Regards

**Comment by DustBytes** [comment] 2023-01-10 16:06
Can we have this feature please.
Since people are used to desktop version. Some features are highly needed.
I have opened few other tickets also.

Should I open a new ticket for this?

Regards,

**Comment by DustBytes** [comment] 2023-01-10 16:13
Ah ok. 
Saw the other one open.

Thank You
