### ISSUE TITLE
"invalid stored block lengths" upgrading from 2.5.2 to 2.15.5 

### ISSUE THREAD

**Issue by antonioaltamura** [igvteam/igv.js#1691] opened 2023-09-21 14:07 UTC
Hello,
upgrading from IGV 2.5.2 to 2.15.5 I'm getting this error on an alignment track on a CRAM file (htsget protocol).
This is the track (at runtime, so the request header, including the range, is generated by IGV)
```
{
    "type": "alignment",
    "sourceType": "htsget",
    "endpoint": "https://our.htsget.service",
    "id": "/reads/bypath/STUDY/by_name:SAMPLE_ID.cram",
    "name": "SAMPLE_ID.cram",
    "headers": {
        "Authorization": "Bearer token",
        "Eof": "true",
        "X-Subregion": "chr1:7365009-7383024",
        "Header-bytes-length": "118535"
    },
    "order": 1
}
```

Inspecting the htsget network requests, on our application running on 2.5.2 I see 3 of them:
```
https://our.htsget.service/reads/bypath/STUDY/by_name:SAMPLE_ID.cram?format=BAM&referenceName=chr1&start=7365009&end=7383024
https://our.htsget.service/data?format=CRAM&study=STUDY&fileId=12345&class=header
https://our.htsget.service/data?format=CRAM&study=STUDY&fileId=12345&class=body&referenceName=chr1&start=7365009&end=7383024
```

while in 2.15.5 I see IGV sends 5 requests:

```
https://our.htsget.service/reads/bypath/STUDY/by_name:SAMPLE_ID.cram?class=header&format=BAM
https://our.htsget.service/data?format=CRAM&study=STUDY&fileId=12345&class=header
https://our.htsget.service/reads/bypath/STUDY/by_name:SAMPLE_ID.cram?format=BAM&referenceName=chr1&start=7365009&end=7383024
https://our.htsget.service/data?format=CRAM&study=STUDY&fileId=12345&class=header
https://our.htsget.service/data?format=CRAM&study=STUDY&fileId=12345&class=body&referenceName=chr1&start=7365009&end=7383024
```

any suggestion on what could be throwing that error?

**Comment by jrobinso** [comment] 2023-09-21 16:02
@antonioaltamura It's really hard to say.  Unfortunately I do not have access to a server to test htsget with, the GA4GH public reference server has been broken for some time.   If you are able to setup or point me to a public test server I will look into it.

2.15.5 is not the latest release, you might try 2.15.11.   Also, if you could try the latest development build available here that would be useful.  https://igv.org/web/snapshot/dist/ That build will be released as 2.16.0 in the near future.   If you could report back here after trying those that would be helpful.

**Comment by jrobinso** [comment] 2023-09-22 18:19
I really don't know, when I get access to a htsget server I will look into it.   There is probably nothing you can do about it other than using the version that works.   If you could narrow it down to a precise version I could look at the diffs but would just be guessing.

The error indicates that the BAM parser is getting bytes that it doesn't expect.

**Comment by brainstorm** [comment] 2023-09-26 06:14
Jim, I just added the (temporary) public BAM endpoint you requested in our issue:

https://htsget.demo.umccr.org/reads/org.umccr.demo.htsget-rs-data/bam/htsnexus_test_NA12878

**Comment by antonioaltamura** [comment] 2023-09-26 14:33
It seems that endpoint misses the CORS header

**Comment by jrobinso** [comment] 2023-09-26 16:02
@brainstorm Thanks for the test file.  As @antonioaltamura notes there are no CORS headers, so I can't test from the browser but i can from Node.    Can you give me a region where there are known alignments?   I'm getting 404 errors when I query for the alignments,  I know this happens if you request a region on a chromosome where there are no alignments.

**Comment by jrobinso** [comment] 2023-09-26 16:18
@brainstorm This is what I'm getting for the reads ticket request for every chromosome I've tried (e.g. https://htsget.demo.umccr.org/reads/org.umccr.demo.htsget-rs-data/bam/htsnexus_test_NA12878?format=BAM&referenceName=22&start=1&end=10100).   I don't think this is correct, BTW,  the spec says the 404 not found error shoudl be returned if the referenceName does not exist.  But it does (22 in the example),  its in the BAM header.  

```
{
  "htsget": {
    "error": "NotFound",
    "message": "could not find byte ranges for reference sequence"
  }
}
```

**Comment by mmalenic** [comment] 2023-09-28 01:20
@jrobinso this file (https://github.com/umccr/htsget-rs/blob/07062a31e000232097a53c6a9fe09f82143294fc/data/bam/htsnexus_test_NA12878.bam) doesn't contain any mapped reads for reference names other than 11 and 20. 

Initially I thought that while other reference names do exist in the header, they are not mapped to any byte ranges in the file. This would mean that no byte ranges could be found, and an error is returned. 

However, I agree that this isn't the right behaviour, and I've outlined this here: https://github.com/umccr/htsget-rs/issues/201.

**Comment by jrobinso** [comment] 2023-09-28 02:28
Ahh, o.k.,  I guess I didn't try 11 and 20.     Yes I think for a spec compliant server an empty array should be returned here, but for my purposes I'll just test with 11 and 20.   Thanks for looking into this.

I personally thing and argued that an empty array should be returned for no referenceName match,  this is what all other tools do that query bams.    But that's not a big deal anymore now that we have a "class=header" option,  at the beginning of this project you just had to hunt and peck.

**Comment by jrobinso** [comment] 2023-09-28 06:18
I found some bam alignments.  Unfortunately everything worked fine.  @antonioaltamura 's issue is with a CRAM, maybe its specific to CRAM.   Could you possibly add the cram file to the server (https://github.com/umccr/htsget-rs/blob/07062a31e000232097a53c6a9fe09f82143294fc/data/cram/htsnexus_test_NA12878.cram).  I tried this but got a 404 error. 
```
https://htsget.demo.umccr.org/reads/org.umccr.demo.htsget-rs-data/cram/htsnexus_test_NA12878
```

**Comment by jrobinso** [comment] 2023-09-28 06:23
@antonioaltamura  It would be helpful if you could try igv.js versions between 2.15.2 and 2.15.5 to narrow the problem down to a specific release.   There are hundreds of commits to look at, but maybe if you could narrow it down a bit I will spot something.   Sorry to ask you for that, but I so far can't reproduce it here.

**Comment by brainstorm** [comment] 2023-09-28 06:25
@jrobinso While writing a bunch of examples for htsget-rs and IGV.js on an upcoming PR in this branch:

https://github.com/umccr/igv.js/tree/umccr_htsget_examples/dev/htsget

I found out that neither CRAM nor BCF seem to be implemented (in IGV.js' Htsget support)? That's why I starting writing up this right now:

https://github.com/igvteam/igv.js/compare/master...umccr:igv.js:support_htsget_cram

Feel free to open the test .htmls from the `dev/htsget` directly and you'll see the error messages for CRAM... BAM and VCF seem to be working fine now after Marko and I fixed CORS at the API gw and S3 bucket levels yesterday night.

**Comment by mmalenic** [comment] 2023-09-28 07:26
@jrobinso That file should be available from the server using `CRAM` as the format: `curl "https://htsget.demo.umccr.org/reads/org.umccr.demo.htsget-rs-data/cram/htsnexus_test_NA12878?format=CRAM"`

**Comment by jrobinso** [comment] 2023-09-28 14:53
@brainstorm  As the original poster here notes his access to CRAM worked until a recent igv.js release, that is the requested format was BAM and backend store CRAM.  The requested format should be independent of the back-end store, at least that's how I interpreted the spec, "_Request data in this format._ "    That's how it was working for the original user until recently.   

I can look into supporting BAM.   IGV itself doesn't support BCF so that won't be possible.  

BTW,  the spec says "The server SHOULD reply with an UnsupportedFormat error if the requested format is not supported." Maybe you are doing that, but I just got a 404 error.

**Comment by jrobinso** [comment] 2023-09-28 15:17
@brainstorm Thanks for getting started on the CRAM.  I did a PR to save myself some typing.   I envisioned htsget servers reading data on the end users behalf then streaming it back in the format requested.  And some implementations do that, clearly the server for the OP here does, who must be wondering what has happened to his ticket :).     The "demo umccr" server is working more like a DRS service or fetcher for signed URLs, just returning urls to the actual data files.   Its valid it just wasn't in my mental model.

With a server such as this the end user needs to have more than just the endpoint and data ID, they also need to know the format of the underlying data store.   There's only 2 possibilities so that's not bad.  If the server returns an "UnsupportedFormat" error I can look for that and inform the user.    I haven't tested any of this on IGV desktop yet it probably needs the same update.

**Comment by jrobinso** [comment] 2023-09-28 16:20
@brainstorm Oops,  well it didn't take too long to convince me that this is going to be really hard (supporting CRAM).  The structure of a CRAM file is nothing like a BAM file,  for one thing thing there are 8 possible compression methods in addition to gzip.    igv.js supports CRAM files with the[   ](https://github.com/GMOD/bam-js) reader, and any solution is going to need to use that.   IGV does this by implementing a "FileHandle" interface (below) for local and remote (https) files.  I don't see anyway to implement this interface with htsget as a backend.

Of course if you know the htsget server is just returning urls to the raw file in the ticket you might be able to implement this, but it would not work in general.    

The alternative would be to dig into the cram-js project and rip out bits and pieces but that is a big undertaking.   So in summary supporting CRAM as a format is more than I can take on.  

We should move these conversations elsewhere, open a new ticket in igv.js if you want to continue but we are well off track now from the subject of this ticket.


```
export interface GenericFilehandle {
    read(buf: Buffer, offset: number, length: number, position: number, opts?: FilehandleOptions): Promise<{
        bytesRead: number;
        buffer: Buffer;
    }>;
    readFile(): Promise<Buffer>;
    readFile(options: BufferEncoding): Promise<string>;
    readFile<T extends undefined>(options: Omit<FilehandleOptions, 'encoding'> | (Omit<FilehandleOptions, 'encoding'> & {
        encoding: T;
    })): Promise<Buffer>;
    readFile<T extends BufferEncoding>(options: Omit<FilehandleOptions, 'encoding'> & {
        encoding: T;
    }): Promise<string>;
    readFile<T extends BufferEncoding>(options: Omit<FilehandleOptions, 'encoding'> & {
        encoding?: T;
    }): T extends BufferEncoding ? Promise<Buffer> : Promise<Buffer | string>;
    readFile(options?: FilehandleOptions | BufferEncoding): Promise<Buffer | string>;
    stat(): Promise<Stats>;
    close(): Promise<void>;
}```

**Comment by jrobinso** [comment] 2023-09-28 16:25
@antonioaltamura Apologies for hijacking your issue,  if you are still reading we have been trying to create an environment that replicates your server.    This has turned out to be more difficult than imagined.   If you were successfully using igv.js prior to 2.5.2 this means you were successfully requesting "BAM" format data from a server with a "CRAM" backing file.  So even if we got the UMCCR server working it would not replicate your situation.

I will continue to search for possible coding changes, but won't be able to test them without your help.  Let me know if this is still an issue for you, and if you are willing to test potential solutions if I find one.

**Comment by antonioaltamura** [comment] 2023-09-28 18:06
@jrobinso any help would be greatly appreciated! Of course I'm available to test any possible solution. Thanks a lot

**Comment by jrobinso** [comment] 2023-09-28 18:16
@antonioaltamura Would you mind trying the 2.15.3 and 2.15.4 releases so we can determine exactly which release breaks? You can get them from the urls below.    The 2.5.3 archive in NPM seems to have a problem.

When we determine the breaking release I will look closely at the commits to see if I can spot the problem

https://igv.org/web/release/2.15.3/dist/

https://igv.org/web/release/2.15.4/dist/

**Comment by antonioaltamura** [comment] 2023-09-29 14:10
Helo @jrobinso I've tried different versions. this is a little report.

```
2.6.1 works
2.7.1 works
2.8.0 works
2.8.6 works
2.9.0 "input buffer is broken"
2.11.0 "invalid stored block lengths"
2.15.1 "invalid stored block lengths"
2.15.3 "invalid stored block lengths"
```

**Comment by jrobinso** [comment] 2023-09-29 18:05
@antonioaltamura Thanks that's helpful.    Could you try setting the format to "bam" explicitly in your configuration, like this?

```
{
    "format": "bam",
    "type": "alignment",
    "sourceType": "htsget",
    "endpoint": "https://our.htsget.service",
    "id": "/reads/bypath/STUDY/by_name:SAMPLE_ID.cram",
    "name": "SAMPLE_ID.cram",
    "headers": {
        "Authorization": "Bearer token",
        "Eof": "true",
        "X-Subregion": "chr1:7365009-7383024",
        "Header-bytes-length": "118535"
    },
    "order": 1
}

I'm trying to figure out where this request is coming from, which is guaranteed to fail.   CRAM is not and never has been supported by igv.js from an htsget request.    You'll note these two requests are not present in the "working" version, setting format explicitly might prevent that.

```
https://our.htsget.service/data?format=CRAM&study=STUDY&fileId=12345&class=header
https://our.htsget.service/data?format=CRAM&study=STUDY&fileId=12345&class=body&referenceName=chr1&start=7365009&end=7383024
````

**Comment by jrobinso** [comment] 2023-09-29 23:29
Also, BTW,  the "endpoint" + "id" thing is supported but not neccessary, in the future you can just use

```
url: ""https://our.htsget.service/reads/bypath/STUDY/by_name:SAMPLE_ID.cram"
```

**Comment by antonioaltamura** [comment] 2023-10-12 15:05
Hello @jrobinso sorry for the late reply. Unfortunately adding the format didn't solve it. Same error.

**Comment by jrobinso** [comment] 2023-10-14 02:25
@antonioaltamura Without a reproducible test case (reproducible by me that is) I don't think there is anything further I can add here.

**Closed** 2024-01-24 04:10 UTC
