### ISSUE TITLE
problem parsing vcf file

### ISSUE THREAD

**Issue by petermchale** [igvteam/igv.js#1079] opened 2020-03-23 19:09 UTC
Here is a vcf (bgzipped), with its index, that igv fails to parse: 

https://drive.google.com/file/d/1ZOSPejgXT8S11qlfnWWZ7ctln7tdXR8m/view?usp=sharing
https://drive.google.com/file/d/1GzX5DW5rTkxvogB2tm4fOwWcRLFKxch5/view?usp=sharing

Concretely, though many variants are parsed correctly, like this one: 

<img width="538" alt="Screen Shot 2020-03-23 at 1 05 00 PM" src="https://user-images.githubusercontent.com/19557137/77353741-23244680-6d07-11ea-8845-c16df124aec1.png">

... the next variant is not: 

<img width="535" alt="Screen Shot 2020-03-23 at 1 06 27 PM" src="https://user-images.githubusercontent.com/19557137/77353792-3fc07e80-6d07-11ea-9080-767d710bea1a.png">

Here's the code in 'dist/igv.js' that I hacked to get the above readouts: 

<img width="703" alt="Screen Shot 2020-03-23 at 1 03 47 PM" src="https://user-images.githubusercontent.com/19557137/77353613-e5272280-6d06-11ea-8801-33d94ff57afc.png">

Is this a problem with the vcf or with igv.js?

**Comment by jrobinso** [comment] 2020-03-23 19:48
It looks like a problem with igv.js,  I can read it in IGV desktop.   I'll look into it.

**Comment by petermchale** [comment] 2020-03-23 23:04
Here is an observation that may help pinpoint the problem: 

igv.js fails to render when the vcf header looks like this: 

```
##fileformat=VCFv4.3
##INFO=<ID=SVCLASS,Number=1,Type=String,Description="">
##INFO=<ID=CALLSET,Number=1,Type=String,Description="">
##INFO=<ID=UNION,Number=.,Type=String,Description=""> 
... 
```

But when I remove the header line containing `SVCLASS`: 

```
##fileformat=VCFv4.3
##INFO=<ID=CALLSET,Number=1,Type=String,Description="">
##INFO=<ID=UNION,Number=.,Type=String,Description="">
##INFO=<ID=END,Number=1,Type=Integer,Description="End coordinate of this variant">
...
```

the vcf gets rendered by igv.js.

**Comment by petermchale** [comment] 2020-03-23 23:14
Not being able to render a vcf in which that `INFO` field is declared in the header is problematic because another tool that I run on that vcf, [truvari](https://github.com/spiralgenetics/truvari), requires that I include that `INFO` field.

**Comment by jrobinso** [comment] 2020-03-23 23:16
OK, that's helpful,  I'll get to the bottom of it.  I assume you are running the latest, but if not give me a version.

**Comment by jrobinso** [comment] 2020-03-24 00:03
@petermchale What version of igv.js are you running?  I can't reproduce your error with the file you provided.

**Comment by petermchale** [comment] 2020-03-24 13:42
`<script type="text/javascript" src="https://cdn.jsdelivr.net/npm/igv@2.4.0/dist/igv.min.js"></script>`

**Comment by petermchale** [comment] 2020-03-24 13:58
@jrobinso The code I hacked to reveal that igv.js is failing to parse some lines is in `dist/igv.js` in an outdated version of the igv.js repo. The package.json file is 

```
{
  "name": "igv",
  "version": "2.3.5",
...
```

**Comment by jrobinso** [comment] 2020-03-24 14:49
Ahh, interesting, I wasn't using the index before (indexed: false),  using the index I can reproduce it.  I'll have this fixed today.

**Comment by petermchale** [comment] 2020-03-24 17:04
Yes, in both contexts I tested, I used: 

  ```
                {
                    type: "variant",
                    format: "vcf",
                    url: "static/data/public/HG00514.BIP-unified.DEL.gt50.lt1000.pacbio.minus_1bp.manta.vcf.gz",
                    indexURL: "static/data/public/HG00514.BIP-unified.DEL.gt50.lt1000.pacbio.minus_1bp.manta.vcf.gz.tbi",
                    name: "DEL.gt50.lt1000 pacbio-unique calls",
                    homrefColor: "rgb(255,0,0)",
                    hetvarColor: "rgb(0,255,0)",
                    homvarColor: "rgb(0,0,255)",
                    //displayMode: "collapsed",
                    //height: 40
                },
```

**Comment by jrobinso** [comment] 2020-03-24 19:00
What you've uncovered here is a strange edge case with igv.js loading bgzip/tabix.   I'll get to the bottom of it, but in the meantime I think you can fix your case by simply changing the visibility window to whole chromosome (-1).    For example
```
 {
                                name: "VCF",
                                type: "variant",
                                format: "vcf",
                                url: "../HG00514.BIP-unified.DEL.gt50.lt1000.pacbio.minus_1bp.manta.vcf.gz",
                                indexURL: "../HG00514.BIP-unified.DEL.gt50.lt1000.pacbio.minus_1bp.manta.vcf.gz.tbi",
                                visibilityWindow: -1
                            }
```

Also, the removal of "svclass" is just shifting the text by enough characters to change the bgzip blocks slightly, which appears to fix the problem but really just hides it.   I think that in all cases some portion of the last text line in the bgzip block is being dropped, which would manifest itself in some missing fields in the popup text for the last variant in that block.    

Thanks for the test data.

**Comment by petermchale** [comment] 2020-03-24 20:52
`visibilityWindow: -1` works for the locus I tested on: 

<img width="1394" alt="Screen Shot 2020-03-24 at 2 42 25 PM" src="https://user-images.githubusercontent.com/19557137/77475479-859c4600-6dde-11ea-95af-bbc9743c0cf6.png">

but not for others: 

<img width="1385" alt="Screen Shot 2020-03-24 at 2 42 38 PM" src="https://user-images.githubusercontent.com/19557137/77475526-977de900-6dde-11ea-9f1e-74843e99bfc1.png">

(It's the track labelled "DEL.gt50.lt1000 pacbio-unique calls".) 

Also, the time taken to render the page now seems to be unworkably long. Is that expected? 

Would an alternative, more robust workaround be to use the uncompressed vcf file without an index?

**Comment by jrobinso** [comment] 2020-03-24 21:22
@petermchale I've found the problem, should have a fix by the end of the day.

**Comment by petermchale** [comment] 2020-03-24 21:27
In the meantime, the following seems to work, robustly: 

```
                {
                    type: "variant",
                    format: "vcf",
                    url: "static/data/public/HG00514.BIP-unified.DEL.gt50.lt1000.pacbio.minus_1bp.manta.vcf",
                    indexed: false,
                    //url: "static/data/public/HG00514.BIP-unified.DEL.gt50.lt1000.pacbio.minus_1bp.manta.vcf.gz",
                    //indexURL: "static/data/public/HG00514.BIP-unified.DEL.gt50.lt1000.pacbio.minus_1bp.manta.vcf.gz.tbi",
                    name: "DEL.gt50.lt1000 pacbio-unique calls",
                    homrefColor: "rgb(255,0,0)",
                    hetvarColor: "rgb(0,255,0)",
                    homvarColor: "rgb(0,0,255)",
                    visibilityWindow: -1,
                    //displayMode: "collapsed",
                    //height: 40
                },
```

**Comment by jrobinso** [comment] 2020-03-24 21:33
Yes, that will work, but you loose the benefit of indexing.

**Comment by petermchale** [comment] 2020-03-24 21:53
Correct, but the vcf file is small enough that the benefit of indexing seems to be insignificant. In any case, I just want a temporary but robust workaround until your permanent fix is implemented. Thanks for your efforts and speedy response. Really appreciate that.

**Comment by jrobinso** [comment] 2020-03-24 21:55
If the vcf is small yes your solution works fine.  In fact it's even better as you load everything once.

**Comment by jrobinso** [comment] 2020-03-25 03:17
@petermchale I think this is fixed.  Could you try the following igv.js?  If it works I'll push this release to npm.

```
 https://igv.org/web/release/2.4.1/dist/igv.js
```

**Comment by petermchale** [comment] 2020-03-25 16:57
Works for `chr10:10,266,955-10,267,361` but not for, say, `chr1:8,668,541-8,669,348`.

**Comment by jrobinso** [comment] 2020-03-25 17:39
OK, its released as version 2.4.1.

**Closed by jrobinso** 2020-03-25 17:39 UTC

**Comment by petermchale** [comment] 2020-03-25 18:12
@jrobinso Does version 2.4.1 fail on `chr1:8,668,541-8,669,348` as it did for me?

**Comment by jrobinso** [comment] 2020-03-25 18:29
@petermchale In what way is it failing?  This is what I see

<img width="1949" alt="Screen Shot 2020-03-25 at 11 27 52 AM" src="https://user-images.githubusercontent.com/933148/77572188-c900be00-6e8b-11ea-8d88-e7a5516f3850.png">

**Comment by petermchale** [comment] 2020-03-25 21:30
I restarted the igv.js-flask server and now it does work for that locus: 

<img width="805" alt="Screen Shot 2020-03-25 at 3 24 10 PM" src="https://user-images.githubusercontent.com/19557137/77587161-fe69d380-6eac-11ea-8d10-d916d3031e8e.png">
<img width="564" alt="Screen Shot 2020-03-25 at 3 24 22 PM" src="https://user-images.githubusercontent.com/19557137/77587166-00cc2d80-6ead-11ea-94cf-ef0faa42b75d.png">

Is that because `igv.js-flask/igvjs/templates/igv.html`, which contains the line ```<script type="text/javascript" src="https://igv.org/web/release/2.4.1/dist/igv.js"></script>``` , is loaded only once when the server is started? 

If so, I could have avoided that confusion by writing some JS to print the current version of igv.js to the web browser's console. That way I would have noticed that the server was not serving the version of igv.js I thought it was. Is there a way to print that diagnostic to the console?

**Comment by jrobinso** [comment] 2020-03-25 21:46
The script should be loaded anytime the web page (not server) is reloaded.  However sometimes the script gets cached in the browser, it should reload if it changes but occasionally it doesn't.

Yes you can log the igv version as follows
```
console.log(igv.version())
```

**Comment by petermchale** [comment] 2020-03-25 22:11
Thanks for the version diagnostic code. 

Just FYI: When I change the version number in the html template, and then do "Empty cache and hard reload" in chrome, `console.log(igv.version())` does not report the updated version number. 
On the other hand, relaunching the flask server does cause `console.log(igv.version())` to report the version currently entered in the html file. 

Thanks for resolving this issue.
