### ISSUE TITLE
removeAllTracks bug and memory issue

### ISSUE THREAD

**Issue by zengzheng123** [igvteam/igv.js#559] opened 2018-03-20 19:40 UTC
It seems that the removeAllTracks() function does not work as expected. tracks.length in the condition is decreased by 1 after each for loop iteration. So only half of the tracks are removed.
```
    igv.Browser.prototype.removeAllTracks = function () {
        var tracks = this.trackViews;
        for (var i = 0; i < **tracks.length**; i++) {
            var track = this.trackViews[i].track;
            this.removeTrack(track);
        }
    };
```

I think this should fix the problem:
```
    igv.Browser.prototype.removeAllTracks = function () {
        for (var i = 0; i < this.trackViews.length; i++) {
            var trackPanelRemoved = this.trackViews[i];
            this.trackContainerDiv.removeChild(trackPanelRemoved.trackDiv);
            this.fireEvent('trackremoved', [trackPanelRemoved.track]);
        }
        this.trackViews.length = 0;
    };
```

And the other issue I have is after removing the track, the memory that track used does not get released. So if I keep removing and adding a track, the memory will keep growing, it's more obvious when using Bam tracks with high coverage. Is there anyway to fix this?

Thank you so much.

Zheng

**Comment by jrobinso** [comment] 2018-03-20 22:08
Thanks,  I'll look into it.   removeAllTracks is not part of the public API,  how are you invoking it?  It could be removed or renamed at any time.

**Comment by zengzheng123** [comment] 2018-03-20 23:17
I just used
```
igv.browser.removeAllTracks();
```

**Comment by zengzheng123** [comment] 2018-03-22 18:49
Btw, I was using igv 1.0.8. I just tested the newest igv beta version with Chrome and Safari. And the memory leaks issue still exists.

**Comment by el1jaC** [comment] 2018-03-26 12:29
@zengzheng123 @jrobinso  IMHO, the issue can be resolved using following trick, but the solution is little bit cleaner.

```javascript
igv.Browser.prototype.removeAllTracks = function () {
        var dels = 0;
	var tracks = this.trackViews;
	for (var i = 0; i < tracks.length - dels; i++) {
		var track = this.trackViews[i].track;
		this.removeTrack(track);
                dels++;
	}
};
```

I've not tested it yet, but i think it can work well.

**Comment by jrobinso** [comment] 2018-03-30 04:50
@zengzheng123 This issue, including the memory leak,  should be resolved now.   If the memory leak persists please reopen.

**Comment by zengzheng123** [comment] 2018-04-05 20:24
@jrobinso Hi, I just had a change to test this memory leak fix.

Before the fix neither removing the entire browser nor removing the tracks would release the memory.

After the fix, removing the entire browser seems to release all the memory. Removing all the tracks seems to release some of the memory, it is much better than before the fix, but the memory still keeps growing slowly if I keep removing and adding the same track.

So I did a simple benchmark, the initial locus was set to a specific region with quite some alignments:
1. Initialize IGV with 2 bam tracks and a vcf track, remove the entire browser, repeat 20 times(I don't remove the browser on the last one). The final memory footprint is 318M. 
2. Initialize IGV with 2 bam tracks and a vcf track. Then I remove all the tracks and add them back, repeat 20 times. The final memory footprint is 421M.

**Comment by jrobinso** [comment] 2018-04-05 22:30
@zengzheng123  OK, we'll keep looking.  The culprit before was mouse handlers on window and document,  which kept references to track objects.    So from your test there is some residual that accumulates,  about 5mb total for the 3 tracks.   If you could repeat that for the BAM and VCF separately it might be informative,  i.e. the problem might be one or the other track type but not both.

**Comment by zengzheng123** [comment] 2018-04-06 00:08
I tested it on a single bam track and a single vcf track separately, removing and adding the track 20 times. It seems that both vcf track and bam track are accumulating some residual. I repeated the test for 3 times and got similar result.

**Comment by zengzheng123** [comment] 2018-04-06 05:57
Btw, "igv.removeBrowser()" is now giving me the following error with the latest master branch build. It was working fine with the master branch build from two days ago.

```
Uncaught TypeError: Cannot read property 'off' of undefined
    at igv.TrackView.dispose (igv-beta.js:50630)
    at igv-beta.js:31285
    at Array.forEach (<anonymous>)
    at igv.Browser.dispose (igv-beta.js:31284)
    at Object.igv.removeBrowser (igv-beta.js:42675)
    at Object.igv.createBrowser (igv-beta.js:42142)
    at init_igv (eval at <anonymous> (jquery-1.12.3.min.js:2), <anonymous>:27:9)
    at igv_jumpto (eval at <anonymous> (jquery-1.12.3.min.js:2), <anonymous>:72:12)
    at HTMLButtonElement.eval (eval at <anonymous> (jquery-1.12.3.min.js:2), <anonymous>:213:12)
    at HTMLButtonElement.dispatch (jquery-1.12.3.min.js:3)
```

**Comment by jrobinso** [comment] 2018-04-06 06:03
OK,  thanks for the report,  but don't use any of the "beta" urls.   I will
be removing that folder soon,  we are moving towards tagged betas.   If you
want to use the latest use  igv.org/web/test,  specifically

<link rel="stylesheet" type="text/css"
href="https://igv.org/web/test/dist/igv-all.css">
<script type="text/javascript"
src="https://igv.org/web/test/dist/igv.min.js"></script>

**Comment by zengzheng123** [comment] 2018-04-06 06:07
I built it from the latest source code myself. I just happened to name the files the same way as the "beta" version.

**Comment by jrobinso** [comment] 2018-04-06 06:08
OK,  I couldn't reproduce the bug in the development branch so I just
merged development -> master.   Try again.

**Comment by zengzheng123** [comment] 2018-04-06 06:15
Thank you so much. "igv.removeBrowser()" is working again.

**Closed** 2018-04-12 21:10 UTC
