### ISSUE TITLE
Missing reads?

### ISSUE THREAD

**Issue by xzhub** [igvteam/igv.js#937] opened 2019-07-17 07:28 UTC
With the latest release 2.2.14 igv.js， I got this screenshot:
<img width="1225" alt="Screen Shot 2019-07-17 at 3 13 06 PM" src="https://user-images.githubusercontent.com/3990687/61355131-43615300-a8a6-11e9-8fa0-eb135c6c5b3c.png">

You can see there are 4 T reads, but there should be 27 T reads according to the popup window.

BAM file:  

[test.bam.gz](https://github.com/igvteam/igv.js/files/3400620/test.bam.gz)

In genomes.json, this alias.txt is used:
`"aliasURL": "alias.txt"`
[alias.txt](https://github.com/igvteam/igv.js/files/3400630/alias.txt)

html code:

```
<script type="text/javascript">

    document.addEventListener("DOMContentLoaded", function () {

        var options =
        {
            genome: "hg19",
            locus: "3:185791817-185791856",
            tracks: [
                {
                    type: 'alignment',
                    format: 'bam',
                    url: 'test.bam',
                    samplingDepth: '2000',
                    alignmentRowHeight: 10,
                    colorBy: "strand",
                    name: 'TEST'
                }
            ]
        };

        var igvDiv = document.getElementById("igv-div");

        igv.createBrowser(igvDiv, options)
                .then(function (browser) {
                    console.log("Created IGV browser");
                })

    });

</script>
```

Please help, thanks!

**Comment by jrobinso** [comment] 2019-07-17 15:56
It is normal for deep coverage regions to be downsampled.    See the properties "samplingDepth" and "samplingWIndowSize" here for settings:  https://github.com/igvteam/igv.js/wiki/Alignment-Track

However when downsampled there should be a black bar under coverage to indicate what was downsampled, which I don't see.   I will look into that.

**Comment by jrobinso** [comment] 2019-07-17 16:33
OK, I found the problem.   In addition to sampling parameters there is another undocumented property "maxRows",  the purpose of which is to keep the browser from freezing in pathological cases.   It is set by default to 1,000,  which seemed like a big number at the time but is not big enough for this case.   You can change this setting as shown below,  however if you don't downsample you might run out of memory on your browser,  or find performance to be very slow.
```
                    {
                        type: 'alignment',
                        format: 'bam',
                        url: '../test.bam',
                        indexURL: '../test.bam.bai',
                        name: 'test',
                        samplingDepth: 10000,
                        maxRows: 10000
                    }
```

**Comment by jrobinso** [comment] 2019-07-17 16:45
Thanks for calling this to my attention,  I have an idea for a short and long term solution for the performance issue with such deep coverage bams.   Will update here when something is available.

**Comment by jrobinso** [comment] 2019-07-17 19:06
OK, I pushed some minor fixes to the snapshot build   With this you can get reasonably good performance with the snapshot build by setting the alignmentRowHeight to a small number.    This means mismatches will be indicated with a colored block, rather than a letter, but that is the tradeoff for viewing deep coverage without downsampling.     Until the next release you can use

```
<script src="https://igv.org/web/snapshot/dist/igv.min.js"></script>
```

For settings I used this on your file with good performance

```
{
   type: 'alignment',
   format: 'bam',
   url: '../test.bam',
    indexURL: '../test.bam.bai',
    name: 'test',
    samplingDepth: 2000,
    alignmentRowHeight: 4
}
```

**Comment by xzhub** [comment] 2019-07-18 06:04
Thank you so much for the quick fix! Appreciated!
I tested it a bit and I got 'Error loading track data':
<img width="1233" alt="Screen Shot 2019-07-18 at 1 58 52 PM" src="https://user-images.githubusercontent.com/3990687/61432868-4de22200-a964-11e9-95e8-2bda66f7a136.png">

Maybe I missing something?

**Comment by jrobinso** [comment] 2019-07-18 06:59
If you can come up with steps to reproduce this I will look at it.  

I have a better fix for your original problem but it will take a week or so before it can be released, the problem of deep coverage alignment files is compex.

**Comment by xzhub** [comment] 2019-07-21 09:18
I am using the same testing scripts above, or add maxRows like this:
```
var options =
        {
            genome: "hg19",
            locus: "3:185791817-185791856",
            tracks: [
                {
                    type: 'alignment',
                    format: 'bam',
                    url: 'test.bam',
                    samplingDepth: '2000',
                    alignmentRowHeight: 10,
                    colorBy: "strand",
                    maxRows: 10000, 
                    name: 'TEST'
                }
            ]
        };
```

No matter how I change the configuration, I will see the 'Error loading track data' error after I comment the local js and enable the snapshot js:

```
    <script src="https://igv.org/web/snapshot/dist/igv.min.js"></script>
    <!-- IGV JS
    <script src="igv.min.js"></script>
    -->
```

**Comment by xzhub** [comment] 2019-07-21 09:43
I can see the web page with "https://igv.org/web/snapshot/dist/igv.js"
```
    <script src="https://igv.org/web/snapshot/dist/igv.js"></script>
```

However, this must be the old version since the mismatch reads count is 4：

<img width="865" alt="Screen Shot 2019-07-21 at 5 41 36 PM" src="https://user-images.githubusercontent.com/3990687/61589602-05826880-abdf-11e9-8dc6-0018438d03d6.png">

**Comment by jrobinso** [comment] 2019-07-21 13:45
You should use  (note the ".min").   I will delete the other one.

 <script src="https://igv.org/web/snapshot/dist/igv.min.js
<https://igv.org/web/snapshot/dist/igv.js>"></script>

**Comment by jrobinso** [comment] 2019-07-21 13:59
@xzhub try setting the indexURL.   indexURL should always be set for BAM files,   it might have worked in the past for small bam files but will blow up for large ones.

**Comment by xzhub** [comment] 2019-07-21 15:01
Still the same error after adding indexURL. I tested with both Chrome and Safari. 

```
<script src="https://igv.org/web/snapshot/dist/igv.min.js"></script>
<div id="igv-div" style="padding-top: 10px;padding-bottom: 10px; border:1px solid lightgray"></div>

<script type="text/javascript">

    document.addEventListener("DOMContentLoaded", function () {

        var options =
        {
            genome: "hg19",
            locus: "3:185791817-185791856",
            tracks: [
                {
                    type: 'alignment',
                    format: 'bam',
                    url: 'test.bam',
                    indexURL: 'test.bam.bai',
                    samplingDepth: '2000',
                    alignmentRowHeight: 4,
                    colorBy: "strand",
                    name: 'TEST'
                }
            ]
        };

        var igvDiv = document.getElementById("igv-div");

        igv.createBrowser(igvDiv, options)
                .then(function (browser) {
                    console.log("Created IGV browser");
                })

    });

</script>
```

<img width="1202" alt="Screen Shot 2019-07-21 at 10 57 47 PM" src="https://user-images.githubusercontent.com/3990687/61592882-6758c780-ac0b-11e9-96bc-7e7014d65637.png">
<img width="561" alt="Screen Shot 2019-07-21 at 10 58 54 PM" src="https://user-images.githubusercontent.com/3990687/61592885-6aec4e80-ac0b-11e9-820c-257b859224d2.png">

**Comment by jrobinso** [comment] 2019-07-21 21:32
Could you zip and attach a complete test to reproduce this,  including your html file?  I can't reproduce it at all with the test.bam you sent me earlier.     Here's my test case, you should be able to run this yourself

```
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="shortcut icon" href="https://igv.org/web/img/favicon.ico">

    <title>igv.js</title>

    <script src="https://igv.org/web/snapshot/dist/igv.min.js"></script>



</head>

<body>


<div id="igv-div" style="padding-top: 10px;padding-bottom: 10px; border:1px solid lightgray"></div>

<script type="text/javascript">

    document.addEventListener("DOMContentLoaded", function () {


        var options =
            {
                genome: "hg19",
                locus: "3:185791817-185791856",
                tracks: [
                    {
                        type: 'alignment',
                        format: 'bam',
                        url: 'https://www.dropbox.com/s/q2cbg77tr5hm3df/deep_coverage.bam?dl=0',
                        indexURL: 'https://www.dropbox.com/s/0zfka7a5gmgbeql/deep_coverage.bam.bai?dl=0',
                        samplingDepth: '2000',
                        alignmentRowHeight: 10,
                        colorBy: "strand",
                        name: 'TEST'
                    }
                ]
            };

        var igvDiv = document.getElementById("igv-div");

        igv.createBrowser(igvDiv, options)
            .then(function (browser) {
                console.log("Created IGV browser");
            })

    });

</script>

</body>

</html>
```

**Comment by xzhub** [comment] 2019-07-22 02:21
I am in China, I can't visit dropbox so I have to change the bam/bai link to local. 
I am still encountering the same issue, however I'd like to ask if there is any other service in igv.min.js that relies on google or dropbox? These services are not accessible from China.

**Comment by xzhub** [comment] 2019-07-22 02:32
Here is the bam and html files I used for testing: [937.tar.gz](https://github.com/igvteam/igv.js/files/3415487/937.tar.gz)

Here is the networking window. I noticed that I always get 416 for one of the requests.
<img width="1233" alt="Screen Shot 2019-07-22 at 10 28 34 AM" src="https://user-images.githubusercontent.com/3990687/61602328-a9195a80-ac6b-11e9-8a56-9d5b8af5a66e.png">

**Comment by jrobinso** [comment] 2019-07-22 02:58
There's something wrong with your index.  I could reproduce the problem with your index file, but after removing and recreating the index with samtools it worked fine.   How did you create this index?

**Comment by xzhub** [comment] 2019-07-22 03:35
That's wired. I used samtools to make the index:
```
samtools index test.bam
```

version:
```
$ samtools

Program: samtools (Tools for alignments in the SAM format)
Version: 0.1.19-44428cd
```

The old version of igv.min.js works fine with it.

I did samtools index again, the new bai is identical to the old one, and the new igv gives me the same error. 

Could you please send me your bai file? I'd like to try it.

**Comment by jrobinso** [comment] 2019-07-22 03:54
Index attached.  I get exactly the same error as you with your original index using ```<script src="https://igv.org/web/release/2.2.14/dist/igv.min.js"></script>```.   In what version of igv.js did this index work?
[test.bam.bai.gz](https://github.com/igvteam/igv.js/files/3415655/test.bam.bai.gz)

**Comment by xzhub** [comment] 2019-07-22 04:15
Indeed, your bai file works! Which version of samtools did you use?

I can't figure out the version of my igv.min.js, so I attached it here. Should be an old version. Let me know if you find out anything.
[igv.min.js.gz](https://github.com/igvteam/igv.js/files/3415681/igv.min.js.gz)

**Comment by jrobinso** [comment] 2019-07-22 04:20
Tje sa,tpp;s versopm is 1.9, but I am working on the theory that  the problem is with igv.min.js.  If I knew which version worked I could git bisect.   Its o.k. I'll find it.    

Having said that the version of samtools you are using is very old, if its really 0.1.19,  and you should really update it.

Looking for clues,  are your bam files all as small as this one?  I'm working on the theory that this is a problem triggered by some combination of samtools and very small bam files.   But that is just a theory.

**Comment by xzhub** [comment] 2019-07-22 04:33
This bam file was extracted from a large bam for testing purpose only. I tested with another small bam, same error. Let me try it with more bam files then get back to you later.

**Comment by jrobinso** [comment] 2019-07-22 04:35
Try with a large bam file.

Whatever this error is its obscure,  no other reports of it, and igv.js is heavily used.   I will find it but really you shouldn't be using an 0.1.x version of samtools, if that's really what it is.

**Comment by jrobinso** [comment] 2019-07-22 05:04
The version of samtools you are using is not creating the same index as version 1.9.  In particular the extent of the first compressed block looks incorrect.   Samtools 1.9 handles this error, as did some earlier version of igv.js apparently,  but it is still incorrect and I wouldn't continue relying on indexes created with this version of samtools.    

I will see if I can code a workaround since others might such indexes.

**Comment by jrobinso** [comment] 2019-07-22 05:30
I pushed a change that catches this error and continues,  the snapshot version should build automatically within the hour.    However the index is wrong, and there are many bugs in samtools 0.1.9 that have been fixed, that version was released in 2013.

**Closed by jrobinso** 2019-07-22 05:30 UTC

**Comment by xzhub** [comment] 2019-07-22 23:02
Samtools 0.1.19-44428cd is the builtin version of Centos 7.x, I am sure there are still a lot of people use this version. Thanks again for your quick response. Now I can confirm the fix has been taken effect and all my bam files work, even with the old samtools index.
