### ISSUE TITLE
Wide feature popup

### ISSUE THREAD

**Issue by mceike** [igvteam/igv.js#1441] opened 2021-12-13 15:26 UTC
Since v2.10.0, feature popups for VCF tracks that contain very long strings in the displayed data seem to default to about 1500 px before truncation, irrespective of available screen estate. This creates problems for smaller screen widths and especially in our embedded setup. E.g. a ClinVar track we use has a long "CLINVARJSON" string and displays like this:
 
![image](https://user-images.githubusercontent.com/2444948/145836616-d5aa2424-0d56-4c9f-ae4b-cfbc2321578c.png)

We've also observed this for: 
- Our annotated VCFs, where the culprit the [VEP CSQ INFO](http://grch37.ensembl.org/info/docs/tools/vep/vep_formats.html#vcfout) field.  
- A VCF track with a long source URL; here the wide popup is when clicking the track label

A sample ClinVar VCF for a region at the beginning of chr 1:
[clinvar_20200626.vcf.gz](https://github.com/igvteam/igv.js/files/7705284/clinvar_20200626.vcf.gz)

**Comment by jrobinso** [comment] 2021-12-13 20:34
Hi, we're working on this, but could you elaborate on what you mean by this?  What is a "dynamic vcf track". and "api string"?

_**A dynamic vcf track with a long api string; here the wide popup is when clicking the track label**_

**Comment by mceike** [comment] 2021-12-13 21:59
Hi, thanks for looking into this and sorry for being unclear - it's a variants VCF track we dynamically generate using an API when loading an analysis, the "api string" is the source field in the popup, in the form `URL: /api/v1/igv/tracks/dynamic/variants/[analysis_ID]/?allele_ids=[ID1],[ID2],[...]`. When the number of variants gets larger, it looks like this when clicking the track label (basically the same problem as with the feature popups):

![image](https://user-images.githubusercontent.com/2444948/145890348-c969d09c-69c8-4a7a-b6bd-6a255099c59d.png)

**Comment by jrobinso** [comment] 2021-12-14 23:39
This should be fixed in the latest release, 2.10.5.  We can't reproduce the track label bug.

**Closed by jrobinso** 2021-12-14 23:39 UTC
