### ISSUE TITLE
Tracks not lining up when loaded via browser.loadTrack?

### ISSUE THREAD

**Issue by sereeena** [igvteam/igv.js#1300] opened 2021-03-30 23:23 UTC
I'm using igv.js version 2.7.9 in my app and when trying to load and display an alignment and variant track together, notice that they are not lined up properly, as seen in this screenshot (where cogs on right are not in line and the variant is not lined up with the reads):
![image](https://user-images.githubusercontent.com/13515255/113068045-05849980-9205-11eb-8f38-635d7e0f39bf.png)   

I noticed that if I manually toggle the "show coverage" on and off, after redrawing itself the tracks are now correctly lined up, but I can't "force" igv to redraw the tracks programmatically as changing the width and height of the overall container doesn't do anything and there is no browser config option for alignment tracks to show/hide the coverage.

Codewise, first I create the browser with a reference genome (I am specifying and serving my own genome file if that makes a difference?), and later I configure it with the 2 tracks I want to see and navigate to a locus:
```
      for (let i=0; i<this.tracks.length; i++) {
        igv.browser.removeTrack(this.tracks[i]);
      }

      if (this.sampleName != "") {
        igv.browser.loadTrack({
          url: "files/"+this.sampleName+"_annotated.vcf.gz",
          name: this.sampleName+"_annotated.vcf.gz",
          type: "variant",
          format: "vcf",
          indexURL: "files/"+this.sampleName+"_annotated.vcf.gz.tbi"
        })
        .then(newTrack => {
          this.tracks.push(newTrack);
        })
        .catch( error => {
          console.error(error);
        });

        igv.browser.loadTrack({
          url: "files/"+this.sampleName+"_realign.bam",
          name: this.sampleName+"_realign.bam",
          type: "alignment",
          indexURL: "files/"+this.sampleName+"_realign.bam.bai"
        })
        .then(newTrack => {
          this.tracks.push(newTrack);
        })
        .catch( error => {
          console.error(error);
        });
      }

      if (this.locus != "") igv.browser.search(this.locus);
```
   
Any ideas for what I can do as a workaround or is this a bug that can be fixed? Thanks

**Comment by jrobinso** [comment] 2021-03-31 00:51
Yes this looks like a bug, and we will fix it.   In the meantime, as a work around, you might try the following, as a temporary workaround until the bug is fixed.   This uses non-API functions so it is not a permanent solution.  Also I didn't try to run this there might be syntax errors, but the idea is to force a repaint after the async search function completes.   If this doesn't work let me know and we will escalate the workarounds

```
if (this.locus != "") {
   igv.browser.search(this.locus)
   .then(ignore => {
         for(let t of this.tracks) {
                 t.trackView.repaintViews();
                 // t.trackView.updateViews(true);    <= try repaintViews first, if that doesn't work use this 
        }   
   })
```

**Comment by sereeena** [comment] 2021-03-31 01:38
Thanks for your quick response. Unfortunately the repaint/update workaround (both types) don't work though.   
I can debug/see it redrawing the track, but it doesn't change the way it lines up with the other tracks.

**Comment by jrobinso** [comment] 2021-03-31 01:57
This is what that toggle does, on the bam track object

```
() => {
                this.showCoverage = !this.showCoverage;
                adjustTrackHeight();
                this.trackView.checkContentHeight();
                this.trackView.repaintViews();
            }
```

where adjustTrackHeight is 
```
const adjustTrackHeight = () => {
            if (!this.autoHeight) {
                const h = 15 +
                    (this.showCoverage ? this.coverageTrack.height : 0) +
                    (this.showAlignments ? this.alignmentTrack.height : 0);
                this.trackView.setTrackHeight(h);
            }
        }
```

**Comment by jrobinso** [comment] 2021-03-31 03:00
The first step to fixing the bug is to reproduce it, and so far I have not been successful.  I am trying to simulate your case with public data,  see the attached html.   Do you see anything different?  

[issue_1300.zip](https://github.com/igvteam/igv.js/files/6233524/issue_1300.zip)

**Comment by jrobinso** [comment] 2021-03-31 03:02
Also, are there any errors in your javascript console?  These could be important.

**Comment by sereeena** [comment] 2021-03-31 05:04
OK so my app uses lit-element in the UI so this is obviously the cause of the problem, and I think it is causing a timing related drawing issue. I understand if you don't find my use case a priority but I appreciate any help you can give.   

It took me a little while to create a test case for you to reproduce the problem. It is not exactly like my code, (which is actually running in electron, not the browser) but I wanted to upload the smallest/simplest code for your testing.

I have a web component which is my "app" and it has other components within it, including a popup dialog which has the IGV chart as its content. I found that because lit-element components have a shadowRoot (encapsulated DOM tree) this caused problems with IGV and I needed to use slots and force my element to render its children not in the shadowRoot but in light DOM so that IGV can find the elements on the page. This seems to work nicely. I didn't add the code for my dialog for simplicity, but this test case shows the exact same issue I am having.

To run you need node installed, after unzipping, cd lit-element-starter-js, then npm ci to get the node packages set up.   
Type npm run serve and navigate browser to localhost:8000/dev/index.html   
There are no errors in the console.   

If you uncomment the following code and run it, the tracks line up without showing coverage! But it only works after a delay, so perhaps it only works after the chart has completed its redraw? And I am not able to get it to re-show the coverage...
```
          setTimeout(() => {
            this.tracks[0].showCoverage = false;
            this.tracks[0].trackView.repaintViews();
          }, 1000);
```   

Here's the code to reproduce:   
[litElementIGV.tar.gz](https://github.com/igvteam/igv.js/files/6233878/litElementIGV.tar.gz)

**Comment by jrobinso** [comment] 2021-03-31 15:12
@sereeena Thanks for the test app, I was able to reproduce it, and although I did not find the cause I did discover that it appears to be fixed in the latest (unreleased) master branch.   Please try the following for your igv import, which is built automatically from master

```
https://igv.org/web/snapshot/dist/igv.esm.js
```

**Comment by sereeena** [comment] 2021-03-31 23:54
Thank you, this build of igv fixes the track lining up issue, but it now seems to have a different bug with displaying my vcf data? It doesn't seem to be occurring in the public data you provided, it is in my vcf file, only occurring for some/most variants and there are no errors in the console. 
   
See the following screenshot which is the same region as the screenshot in my original post. The sample related information for the variant in the vcf track is missing, and I can no longer click on the variant region to pop up the window showing the data from the vcf. If I change the track config to "collapse" I get the popup when I click on the variant, if "expand" I can't and the "sample" part of the variant is missing.    

I am definitely using the same data files as before, if I switch between v2.7.9 and your snapshot this is what happens:     

![image](https://user-images.githubusercontent.com/13515255/113224748-99249b80-92d3-11eb-9662-23bbf1a65355.png)

**Comment by jrobinso** [comment] 2021-04-01 01:01
Are there any errors in the javascript console?   Also, is it possible to share a small VCF that reproduces this issue?  If there is private data involved perhaps you can create a simulated VCF by, for example,  changing chromosome names.

**Comment by sereeena** [comment] 2021-04-01 02:52
No there are no errors in the console. Here is the vcf, put it and the tbi in the files/ folder, and put the my-element.js file and the new igv.esm.min.js file in the root directory of the project and run as before, then try to click on the variant shown.   

[modified.tar.gz](https://github.com/igvteam/igv.js/files/6240610/modified.tar.gz)

**Comment by jrobinso** [comment] 2021-04-01 05:15
OK thanks for the data, this should be fixed now as well.   Try  ```https://igv.org/web/snapshot/dist/igv.esm.js```

**Comment by sereeena** [comment] 2021-04-01 06:29
Confirmed, it's all working well. Thank you!

**Closed** 2021-04-01 15:27 UTC
