### ISSUE TITLE
Issue with Loading Large GWAS Data Track in igv.js

### ISSUE THREAD

**Issue by yrjia1015** [igvteam/igv.js#1825] opened 2024-06-06 13:10 UTC
Hello igv.js Team,

First of all, thank you for developing igv.js. It's been incredibly helpful for integrating genomic data visualization into our web applications.

I am currently encountering an issue when trying to load large GWAS data tracks in the browser. While testing, I found that loading a file size of 300MB works fine, but when attempting to upload a file of approximately 550MB, I receive the following error:

Cannot read properties of undefined (reading 'split')

Could this error be related to the file size being too large, or is there another aspect I should consider? Any advice on how to handle larger files or if there’s a workaround to this issue would be greatly appreciated.

Thank you!

**Comment by jrobinso** [comment] 2024-06-06 18:29
Its likely the file size but I can't say for sure based on that message alone.   If you can share your file I will look at it,  send email to igv-team@broadinstitute.org and we can send you a secure dropbox link.

WRT larger files, if you do not need the whole genome view you can tabix index the GWAS file (see https://www.htslib.org/doc/tabix.html).

**Comment by yrjia1015** [comment] 2024-06-07 00:28
Thank you for your prompt response and for offering to examine our file. We understand that the issue might be related to the file size, and we appreciate your suggestion to use a Tabix index. However, for our specific needs, we require a whole genome view, which necessitates working with the entire file.
﻿
We have sent an email to igv-team@broadinstitute.org as advised. Thank you again for your support and assistance in resolving this issue.

**Comment by jrobinso** [comment] 2024-06-07 02:33
Another option with a file that size is to downsample it,  you aren't going to be able to see all the points in whole genome view anyway.   You might even consider a downsampled file for a whole genome view track,  and a tabix indexed file for zoomed in views.

**Comment by jrobinso** [comment] 2024-06-07 03:28
@yrjia1015 OK, thanks for the test data.   The problem is caused by the file size.    For the moment igv.js cannot handle a file of this size, the limit is probably ~ 500 MB in Chrome,  and ~1 GB in Firefox and Safari.    I did confirm your file loads in Safari, however performance is poor.  

This is possibly fixable in igv.js, we will leave this issue open as a bug for now.    In the meantime your options are to either downsample the file to a smaller size, or index it, as indicated above.

**Comment by jrobinso** [comment] 2024-06-10 15:57
This is now fixed and will be included in the next release.  You can try it now by building from source, or installing from https://igv.org/web/snapshot/dist/

**Closed** 2024-06-18 18:12 UTC

**Comment by yrjia1015** [comment] 2024-06-20 04:42
Thank you for your patience and prompt resolution of the issue I raised. I appreciate the update and look forward to trying the new release.
